// The VSOP87 generator (PM-28): it reads the archive's blocks, keeps the terms the table keeps, refuses any archive but the pinned one, and — given the official
// archive in VSOP87D_EAR — writes the committed table byte for byte. Without the archive (it is not in the repository) that last test is skipped and says so.
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, test } from "node:test";
import { parseArchive, PINNED_SHA256, readArchive, render, seriesOf, sha256, TABLE } from "./gen-vsop87.ts";

const dir = mkdtempSync(join(tmpdir(), "vsop87-"));
after(() => rmSync(dir, { recursive: true, force: true }));

const head = (variable: number, power: number, n: number): string =>
  ` VSOP87 VERSION D4    EARTH     VARIABLE ${variable} (LBR)       *T**${power}    ${String(n).padStart(3)} TERMS    HELIOCENTRIC DYNAMICAL ECLIPTIC AND EQUINOX OF THE DATE`;
const term = (i: number, a: number, b: number, c: number): string =>
  ` 4310 ${String(i).padStart(4)}  0  0  1  0  0  0  0  0  0  0  0  0 -0.00748171065    -0.03256824823 ${a.toFixed(11).padStart(18)} ${b.toFixed(11)} ${c.toFixed(11).padStart(19)}`;
/** A small archive of the same shape: L and R with two powers each, one B block, terms above and below the thresholds. */
const MINI = [
  head(1, 0, 3), term(1, 1.75347045673, 0, 0), term(2, 0.03341656456, 4.66925680417, 6283.0758499914), term(3, 5e-10, 1, 2),
  head(1, 1, 1), term(1, 6283.31966747491, 0, 0),
  head(2, 0, 1), term(1, 0.00000279620, 3.19870156017, 84334.66158130829),
  head(3, 0, 2), term(1, 1.00013988784, 0, 0), term(2, 9e-9, 1, 2),
].join("\n");

test("the blocks of an archive: each variable and power, the terms in the archive's order, the header's count checked", () => {
  const a = parseArchive(MINI);
  assert.deepEqual([...a.keys()], [1, 2, 3]);
  assert.deepEqual(a.get(1)!.get(0), [[1.75347045673, 0, 0], [0.03341656456, 4.66925680417, 6283.0758499914], [5e-10, 1, 2]]);
  assert.throws(() => parseArchive(MINI.replace(head(1, 1, 1), head(1, 1, 2))), /the header says 2 terms, the block holds 1/);
  assert.throws(() => parseArchive(term(1, 1, 1, 1)), /before any header/);
  assert.throws(() => parseArchive(`${head(1, 0, 1)}\n 4310 1 0 0 x y z`), /not a term line/);
});

test("the kept terms: |A| at or above the threshold, nothing reordered, and the residual of what was dropped", () => {
  const a = parseArchive(MINI);
  const L = seriesOf(a, 1, 1e-9);
  assert.deepEqual(L.powers[0], [[1.75347045673, 0, 0], [0.03341656456, 4.66925680417, 6283.0758499914]]);
  assert.deepEqual([L.total, L.kept, L.residual], [4, 3, 5e-10]);
  const R = seriesOf(a, 3, 1e-8);
  assert.deepEqual([R.total, R.kept, R.residual], [2, 1, 9e-9]);
  assert.equal(R.powers.length, 6, "every power has its block, empty or not");
  assert.throws(() => seriesOf(a, 4, 1e-9), /no variable 4/);
});

test("the table: its header names the archive and the pinned hash, and the series are written as JavaScript prints the numbers", () => {
  const text = render(parseArchive(MINI));
  assert.match(text, new RegExp(`SHA-256 of the archive: ${PINNED_SHA256}`));
  assert.match(text, /generated by scripts\/astro\/gen-vsop87\.ts/);
  assert.match(text, /export const EARTH_L: Vsop87Series = \[\n {2}\/\/ T\^0: 2 terms\n {2}\[\n {4}\[1\.75347045673, 0, 0\],\n {4}\[0\.03341656456, 4\.66925680417, 6283\.0758499914\],\n {2}\],/);
  assert.match(text, /\/\/ T\^5: 0 terms\n {2}\[\n\n {2}\],/, "an empty power keeps its block");
  assert.doesNotMatch(text, /5e-10|9e-9/, "dropped terms are not written");
  assert.doesNotMatch(text, /VARIABLE 2|3\.19870156017/, "the latitude B is not part of the table");
});

test("an archive that is not the pinned one is refused", () => {
  const p = join(dir, "VSOP87D.ear");
  writeFileSync(p, MINI);
  assert.notEqual(sha256(readFileSync(p)), PINNED_SHA256);
  assert.throws(() => readArchive(p), /is not the pinned 8b160c85/);
});

test("the committed table names the pinned archive", () => {
  const committed = readFileSync(TABLE, "utf8");
  assert.match(committed, new RegExp(`SHA-256 of the archive: ${PINNED_SHA256}`));
  assert.match(committed, /L keeps 818 of 1080 terms/);
  assert.match(committed, /R keeps 213 of 997 terms/);
});

const archive = process.env["VSOP87D_EAR"];
test("the official archive gives the committed table byte for byte (set VSOP87D_EAR to the archive's path)", { skip: archive === undefined ? "VSOP87D_EAR is not set: the archive is not in the repository" : false }, () => {
  assert.equal(render(readArchive(archive!)), readFileSync(TABLE, "utf8"));
});
