export * from "./types.ts";
export { resolvePolicy, baselineFacts, matchedKeys, summariseRedFlags, SERIOUS_RED_FLAGS } from "./policy.ts";
export { normalize, applies, qualityOf, sourceOf, type Normalized, type NormalizedFinding, type Conflict, type NormalizeInput } from "./normalize.ts";
export { scorePatterns, scorePattern, scoreElements, scoreElement, bandOf, type ScoredPattern, type ScoredElement, type EvidenceFor, type EvidenceAgainst, type Band } from "./patterns.ts";
export { buildReference, profileParamsFor, type ReferenceBlock, type ReferenceInput, type SeasonBasis } from "./reference.ts";
export { synthesizePanel, observedPanel, wuxingFunction, bagang, yinYangOf, type PanelResult, type BagangScalars, type Alignment, type YinYang, type Projection } from "./panel.ts";
export { fitFormula, fitFormulas, formulaVector, cost, bestScale, strengthOf, candidateFormulaIds, passesSymptomFit, recomputeTier, compositionOf, coreFitOf, dimensionWeight, type FormulaFit, type CompositionRow, type PanelVector, type Tier, type Strength, type Role } from "./formulas.ts";
export { herbVector, compositionVector, modificationPool, classicalModifications, greedyModify, modifyFormula, type ClassicalModification, type ResidualStep, type ResidualModification } from "./modify.ts";
export { saturation, burdenGrowth, typicalDose, doseBandOf, herbAtDose, processingOf, applyPairings, compositionAction, type AmountBand, type HerbAction, type HerbAtDoseOptions, type AppliedPairing, type PairingOutcome, type CompositionRow as RxRow, type PrescriptionTables, type CompositionAction } from "./prescription/herbs.ts";
export { classicalRows, contributions, measureRoles, formulaMechanism, analyseFormula, type ClassicalRows, type HerbContribution, type RoleReading, type RoleCheck, type RoleReport, type RoleOptions, type MechanismComponent, type HerbMechanism, type Mechanism } from "./prescription/formula.ts";
export { verifyLibrary, passing, type FormulaVerification, type IndicationCheck, type DirectionCheck, type VerificationInput } from "./prescription/verify.ts";
export { reconcile, kappaOf, mixedKinds, patternElements, type Verdict, type Confidence, type MixedKind, type PresentedPattern, type TieBreak, type Differential, type DifferentialSymptom, type ReconcileInput } from "./reconcile.ts";
export { orient, checkConsistency, type Orientation, type ConsistencyFlag, type Channel, type ExteriorKind, type Lean, type DeficiencyLean } from "./orient.ts";
export { evaluateSafety, formulaNature, incompatiblePairs, allergyMatches, type SafetyInput, type SafetyReport, type SafetyItem, type SafetySubject, type SuppressedItem, type FiredRule, type Candidate, type FormulaNature } from "./safety.ts";
export { explain, citationsOf, type TraceItem, type ExplainInput, type PriorBlock } from "./explain.ts";
export { nextQuestions, isAsked, type InquiryState, type NextQuestions, type QuestionSuggestion, type QuestionReason, type StopReason } from "./questionnaire.ts";
export { assess, ENGINE_VERSION, type AssessInput, type Assessment } from "./assess.ts";
export { recommend, MAX_RECOMMENDED_FORMULAS, type Recommendations, type FormulaRecommendation, type FoodRecommendation, type AcupointRecommendation, type RecommendInput, type RecommendResult } from "./recommend.ts";
export { scoreConstitution, susceptibilityAt, BALANCED, MIN_ANSWERED_SHARE, type ConstitutionResult, type ConstitutionScore, type ConstitutionLevel, type ConstitutionBlock, type SeasonSusceptibility, type SusceptibilityItem } from "./constitution.ts";
export { featureBand, featuresOf, comparePatterns, KEY_SHARE, COMMON_SHARE, DISTINGUISHES, MAX_COMPARED, MAX_QUESTIONS, type Feature, type FeatureBand, type Comparison, type ComparedFeature, type ComparedQuestion } from "./learn.ts";
