"""The review sheet for the Mainland-usage reviewer (docs/post-mvp/design/simplified-chinese.md §5.2): what the converter did that is not plain character conversion.

    pnpm i18n:review-hans            # prints Markdown
    pnpm i18n:review-hans -- --out review/hans-review.md

Sections: the overrides in effect · strings converted at vocabulary level (tw2sp differs from character-by-character t2s) · source-text results and mismatches ·
the glossary terms with their Simplified form · UI catalogue messages at vocabulary level.
"""
from __future__ import annotations

import json
import sys

from collections import Counter
from difflib import SequenceMatcher

from opencc import OpenCC

from . import hans

_t2s = OpenCC("t2s")


def word_changes(pairs: list[tuple[str, str]]) -> Counter:
    """The distinct fragments where the vocabulary-aware result differs from character-by-character conversion: (Traditional, Simplified now, Simplified by characters)."""
    seen: Counter = Counter()
    for trad, simp in pairs:
        chars = _t2s.convert(trad)
        if chars == simp:
            continue
        ops = [op for op in SequenceMatcher(None, chars, simp, autojunk=False).get_opcodes()]
        spans: list[list[int]] = []
        for tag, i1, i2, j1, j2 in ops:
            if tag == "equal":
                continue
            if spans and i1 - spans[-1][1] <= 1 and j1 - spans[-1][3] <= 1:
                spans[-1][1], spans[-1][3] = i2, j2
            else:
                spans.append([i1, i2, j1, j2])
        for i1, i2, j1, j2 in spans:
            a, b = max(0, i1 - 1), min(len(chars), i2 + 1)
            c, d = max(0, j1 - 1), min(len(simp), j2 + 1)
            seen[(trad[a:b] if len(chars) == len(trad) else chars[a:b], simp[c:d], chars[a:b])] += 1
    return seen


def sheet() -> str:
    conv = hans.Converter()
    strings = hans.collect()
    sources = hans.source_map()
    out = ["# Simplified Chinese — review sheet", "", "Generated by `pnpm i18n:review-hans`; not committed. Edit `scripts/i18n/hans-overrides.json` to change a result.", ""]
    ov = json.loads(hans.OVERRIDES.read_text(encoding="utf-8"))
    out += ["## Overrides in effect", "", "| Kind | From | To | Reason |", "|---|---|---|---|"]
    for kind in ("phrases", "exact", "keys", "keep"):
        for k, v in ov.get(kind, {}).items():
            out.append(f"| {kind} | {k} | {v.get('to', '(kept)')} | {v['reason']} |")
    vocab, mismatch, sourced = [], [], 0
    for s in sorted(strings):
        if strings[s]:
            continue
        r = conv.convert(s, source=sources.get(s))
        if r.rule == "source":
            sourced += 1
        elif s in sources:
            mismatch.append((s, sources[s], r.text))
        if r.rule in ("opencc", "phrase") and r.text != _t2s.convert(s):
            vocab.append((s, r.text))
    words = word_changes(vocab)
    out += ["", f"## Word-level changes in the knowledge base ({len(words)} distinct)", "", "| Traditional | Now | By characters alone | Occurrences |", "|---|---|---|---|"]
    out += [f"| {t} | {n} | {c} | {k} |" for (t, n, c), k in sorted(words.items(), key=lambda kv: (-kv[1], kv[0]))]
    out += ["", f"## Knowledge-base strings converted at vocabulary level ({len(vocab)})", "", "| Traditional | Simplified |", "|---|---|"]
    out += [f"| {a} | {b} |" for a, b in vocab]
    out += ["", f"## Quotations", "", f"{sourced} quotations use the Simplified source text exactly. Mismatches (the source does not round-trip; the converted text is used): {len(mismatch)}", ""]
    out += [f"- {a}\n  - source: {b}\n  - used: {c}" for a, b, c in mismatch]
    gloss = json.loads((hans.DATA / "glossary.json").read_text(encoding="utf-8"))["items"]
    out += ["", f"## Glossary terms ({len(gloss)})", "", "| Traditional | Simplified | English |", "|---|---|---|"]
    out += [f"| {g['zh-Hant']} | {conv.convert(g['zh-Hant']).text} | {g['en']} |" for g in gloss]
    cat = []
    for f in sorted((hans.CATALOGS / "zh-Hant").glob("*.json")):
        for key, msg in json.loads(f.read_text(encoding="utf-8")).items():
            for text in ([msg] if isinstance(msg, str) else msg.values()):
                r = conv.convert(text, key=key)
                if r.rule in ("opencc", "phrase", "key") and r.text != _t2s.convert(text):
                    cat.append((key, text, r.text))
    cw = word_changes([(t, r) for _k, t, r in cat])
    out += ["", f"## Word-level changes in the interface ({len(cw)} distinct)", "", "| Traditional | Now | By characters alone | Occurrences |", "|---|---|---|---|"]
    out += [f"| {t} | {n} | {c} | {k} |" for (t, n, c), k in sorted(cw.items(), key=lambda kv: (-kv[1], kv[0]))]
    out += ["", f"## Interface messages converted at vocabulary level ({len(cat)})", "", "| Key | Traditional | Simplified |", "|---|---|---|"]
    out += [f"| {k} | {a} | {b} |" for k, a, b in cat]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = sheet()
    if "--out" in sys.argv:
        path = sys.argv[sys.argv.index("--out") + 1]
        open(path, "w", encoding="utf-8").write(text)
        print(f"wrote {path}")
    else:
        sys.stdout.write(text)
