"""Curated formula table (MVP library, 33 formulas). Composition and roles are checked by build_formulas.py:
  · 經方 with a TCM-Library entry or a 金匱要略 passage: classical amounts are PARSED from the original text;
  · 時方: every herb must be found near the formula's heading in the named source book (reported as
    composition_check; unverified herbs are listed, never silently accepted).

herbs = (name, role, typical_g[, note]); roles 君臣佐使 follow the 方劑學 textbook analysis and are
`role_status: textbook-unreviewed`. typical_g is a textbook-typical amount used ONLY to derive relative
proportions for the engine (it is not shown to users by default; SOP D5, scope profiles).
"""

J, S = "經方", "時方"

FORMULAS = [
    dict(id="F_MAHUANG", zh="麻黃湯", en="Mahuang Tang (Ephedra Decoction)", school=J, source=dict(book="傷寒論", ref="shanghan-035"),
         classical=dict(lib="library/fangji/jingfang/mahuangtang/mahuangtang_001.md"), patterns=["EX1"], principle="辛溫發汗、宣肺平喘",
         herbs=[("麻黃", "君", 9), ("桂枝", "臣", 6), ("杏仁", "佐", 9), ("炙甘草", "使", 3)],
         core=["S_AVERSION_COLD", "S_NO_SWEAT", "S_BODY_ACHE", "S_HEADACHE", "P_FLOAT", "P_TIGHT"],
         fangyi="麻黃發汗解表、宣肺平喘為君；桂枝助麻黃發汗、溫通經脈為臣；杏仁降肺氣助平喘為佐；炙甘草調和諸藥為使。",
         cautions=["表虛自汗、體虛外感、血虛、失血者忌用", "高血壓、心悸、甲亢者慎用", "中病即止，不可過汗"]),
    dict(id="F_GUIZHI", zh="桂枝湯", en="Guizhi Tang (Cinnamon Twig Decoction)", school=J, source=dict(book="傷寒論", ref="shanghan-053"),
         classical=dict(lib="library/fangji/jingfang/guizhitang/guizhitang_001.md"), patterns=["EX2", "EX4"], principle="解肌發表、調和營衛",
         herbs=[("桂枝", "君", 9), ("芍藥", "臣", 9), ("生薑", "佐", 9), ("大棗", "佐", 12), ("炙甘草", "使", 6)],
         core=["S_SPONTANEOUS_SWEAT", "S_AVERSION_WIND", "S_FEVER", "P_FLOAT", "P_MODERATE"],
         fangyi="桂枝解肌發表、溫通衛陽為君；芍藥益陰斂營為臣，桂芍相配一散一收、調和營衛；生薑助桂枝解肌、大棗助芍藥益營為佐；炙甘草調和諸藥為使。服後啜熱稀粥以助藥力。",
         cautions=["表實無汗者忌用", "溫熱病、陰虛火旺者不宜", "服後忌生冷、黏滑、肉麵、五辛、酒酪（原方服法）"]),
    dict(id="F_YINQIAO", zh="銀翹散", en="Yinqiao San (Lonicera and Forsythia Powder)", school=S, source=dict(book="溫病條辨", ref="上焦篇", prefix="526", heading="银翘散"),
         patterns=["EX3"], principle="辛涼透表、清熱解毒",
         herbs=[("金銀花", "君", 15), ("連翹", "君", 15), ("薄荷", "臣", 6), ("牛蒡子", "臣", 9), ("荊芥穗", "臣", 5), ("淡豆豉", "臣", 5),
                ("桔梗", "佐", 6), ("竹葉", "佐", 4), ("蘆根", "佐", 15), ("甘草", "使", 5)],
         core=["S_FEVER", "S_SORE_THROAT", "S_THIRST_LIGHT", "T_TIP_RED", "P_FLOAT", "P_RAPID"],
         fangyi="金銀花、連翹辛涼透邪、清熱解毒為君；薄荷、牛蒡子疏風散熱、清利頭目、解毒利咽，荊芥穗、淡豆豉辛散透表為臣；竹葉清上焦熱、蘆根清熱生津，桔梗宣肺利咽為佐；甘草調和諸藥為使。",
         cautions=["外感風寒、無汗惡寒者不宜", "不宜久煎（芳香輕清，「過煮則味厚入中焦」）", "脾胃虛寒者慎用"]),
    dict(id="F_SANGJU", zh="桑菊飲", en="Sangju Yin (Mulberry Leaf and Chrysanthemum Drink)", school=S, source=dict(book="溫病條辨", ref="上焦篇", prefix="526", heading="桑菊饮"),
         patterns=["EX3"], principle="疏風清熱、宣肺止咳",
         herbs=[("桑葉", "君", 7.5), ("菊花", "君", 3), ("薄荷", "臣", 2.5), ("連翹", "臣", 5), ("杏仁", "佐", 6), ("桔梗", "佐", 6), ("蘆根", "佐", 6), ("甘草", "使", 2.5)],
         core=["S_COUGH_PHLEGM_YELLOW", "S_FEVER", "S_THIRST_LIGHT", "S_HEADACHE", "P_FLOAT"],
         fangyi="桑葉、菊花疏散風熱、宣肺止咳為君；薄荷助疏風，杏仁、桔梗宣降肺氣為臣佐；連翹清熱、蘆根清熱生津為佐；甘草調和諸藥為使。",
         cautions=["風寒咳嗽者不宜", "脾胃虛寒者慎用"]),
    dict(id="F_SIJUNZI", zh="四君子湯", en="Sijunzi Tang (Four Gentlemen Decoction)", school=S, source=dict(book="太平惠民和劑局方", ref="卷三", prefix="059", heading="四君子汤"),
         patterns=["SP1"], principle="益氣健脾",
         herbs=[("人參", "君", 9), ("白朮", "臣", 9), ("茯苓", "佐", 9), ("炙甘草", "使", 6)],
         core=["S_POOR_APPETITE", "S_LOOSE_STOOL", "S_FATIGUE", "S_LAZY_SPEAK", "T_BODY_PALE"],
         fangyi="人參大補元氣、健脾養胃為君；白朮健脾燥濕為臣；茯苓滲濕健脾為佐，與白朮相配則健脾祛濕之功益著；炙甘草益氣和中、調和諸藥為使。",
         cautions=["實證、熱證、陰虛火旺者不宜", "人參不宜與藜蘆、五靈脂同用"],
         modifications=[
             dict(id="M_SIJUNZI_YIGONG", result="異功散", add=[("陳皮", "佐", 6)], remove=[], when=["S_EPIGASTRIC_FULLNESS", "S_POSTPRANDIAL_BLOAT"], source=dict(book="小兒藥證直訣", prefix="133", heading="异功散")),
             dict(id="M_SIJUNZI_LIUJUNZI", result="六君子湯", add=[("陳皮", "佐", 6), ("半夏", "佐", 9)], remove=[], when=["S_PHLEGM_COPIOUS", "S_NAUSEA"], source=dict(book="醫方集解", prefix="087", heading="六君子汤")),
             dict(id="M_SIJUNZI_XIANGSHA", result="香砂六君子湯", add=[("陳皮", "佐", 6), ("半夏", "佐", 9), ("木香", "佐", 6), ("砂仁", "佐", 3)], remove=[], when=["S_EPIGASTRIC_PAIN", "S_POSTPRANDIAL_BLOAT", "S_PHLEGM_COPIOUS"], source=dict(book="醫方集解", prefix="087", heading="香砂六君子汤")),
         ]),
    dict(id="F_SHENLING", zh="參苓白朮散", en="Shen Ling Bai Zhu San (Ginseng, Poria and White Atractylodes Powder)", school=S, source=dict(book="太平惠民和劑局方", ref="卷三", prefix="059", heading="参苓白术散"),
         patterns=["SP1"], principle="益氣健脾、滲濕止瀉",
         herbs=[("人參", "君", 10), ("白朮", "君", 10), ("茯苓", "君", 10), ("山藥", "臣", 10), ("蓮子", "臣", 5), ("白扁豆", "佐", 7.5), ("薏苡仁", "佐", 5),
                ("砂仁", "佐", 5), ("桔梗", "佐", 5), ("甘草", "使", 10)],
         core=["S_POOR_APPETITE", "S_LOOSE_STOOL", "S_FATIGUE", "S_POSTPRANDIAL_BLOAT", "T_TOOTHMARK_EDGE"],
         fangyi="人參、白朮、茯苓益氣健脾滲濕為君；山藥、蓮子助君藥健脾益氣、兼能止瀉為臣；白扁豆、薏苡仁健脾滲濕，砂仁醒脾和胃、行氣化滯，桔梗宣肺利氣、載藥上行為佐；甘草健脾和中、調和諸藥為使。",
         cautions=["濕熱內盛、陰虛火旺者不宜", "不宜與藜蘆、五靈脂同用（含人參）"]),
    dict(id="F_LIZHONG", zh="理中丸", en="Lizhong Wan (Regulate the Middle Pill)", school=J, source=dict(book="傷寒論", ref="shanghan-386"),
         classical=dict(lib="library/fangji/jingfang/lizhongwan/lizhongwan_001.md"), patterns=["SP2"], principle="溫中祛寒、補氣健脾",
         herbs=[("乾薑", "君", 9), ("人參", "臣", 9), ("白朮", "佐", 9), ("炙甘草", "使", 9)],
         core=["S_ABD_PAIN_PREFER_WARM_PRESS", "S_FEAR_COLD", "S_LOOSE_STOOL", "S_PREFER_HOT_FOOD", "T_COAT_SLIPPERY"],
         fangyi="乾薑溫中祛寒為君；人參補氣健脾為臣；白朮燥濕健脾為佐；炙甘草益氣和中、調和諸藥為使。",
         cautions=["陰虛內熱、實熱證者忌用", "孕婦慎用乾薑"],
         modifications=[dict(id="M_LIZHONG_FUZI", result="附子理中丸", add=[("附子", "君", 6)], remove=[], when=["S_COLD_LIMBS", "S_LOW_BACK_COLD"], source=dict(book="太平惠民和劑局方", prefix="059", heading="附子理中"))]),
    dict(id="F_BUZHONG", zh="補中益氣湯", en="Buzhong Yiqi Tang (Tonify the Middle and Augment the Qi Decoction)", school=S, source=dict(book="脾胃論", ref="卷中", prefix="614", heading="补中益气汤"),
         patterns=["SP3"], principle="補中益氣、升陽舉陷",
         herbs=[("黃耆", "君", 18), ("人參", "臣", 6), ("白朮", "臣", 9), ("炙甘草", "臣", 9), ("當歸", "佐", 3), ("陳皮", "佐", 6), ("升麻", "使", 6), ("柴胡", "使", 6)],
         core=["S_PROLAPSE_SENSATION", "S_FATIGUE", "S_SHORT_BREATH", "S_LAZY_SPEAK"],
         fangyi="黃耆補中益氣、升陽固表為君；人參、白朮、炙甘草補氣健脾為臣；當歸養血和營，陳皮理氣和胃為佐；升麻、柴胡升舉清陽為使（兼佐）。",
         cautions=["陰虛發熱、內熱熾盛者不宜", "實證、肝陽上亢者忌用"]),
    dict(id="F_ERCHEN", zh="二陳湯", en="Erchen Tang (Two Matured Ingredients Decoction)", school=S, source=dict(book="太平惠民和劑局方", ref="卷四", prefix="059", heading="二陈汤"),
         patterns=["SP4"], principle="燥濕化痰、理氣和中",
         herbs=[("半夏", "君", 15), ("橘紅", "臣", 15), ("茯苓", "佐", 9), ("炙甘草", "使", 4.5)],
         core=["S_PHLEGM_COPIOUS", "S_CHEST_OPPRESSION", "S_NAUSEA", "T_COAT_WHITE_GREASY", "P_SLIPPERY"],
         fangyi="半夏燥濕化痰、降逆和胃為君；橘紅理氣行滯、燥濕化痰為臣，二藥相配使氣順則痰降；茯苓健脾滲濕為佐；炙甘草調和諸藥為使。",
         cautions=["陰虛燥咳、吐血、消渴者忌用", "半夏須炮製；孕婦慎用", "不宜與烏頭類同用"]),
    dict(id="F_PINGWEI", zh="平胃散", en="Pingwei San (Calm the Stomach Powder)", school=S, source=dict(book="太平惠民和劑局方", ref="卷三", prefix="059", heading="平胃散"),
         patterns=["SP4"], principle="燥濕運脾、行氣和胃",
         herbs=[("蒼朮", "君", 15), ("厚朴", "臣", 9), ("陳皮", "佐", 9), ("炙甘草", "使", 4)],
         core=["S_EPIGASTRIC_FULLNESS", "S_BODY_HEAVY", "S_POOR_APPETITE", "T_COAT_WHITE_GREASY"],
         fangyi="蒼朮燥濕運脾為君；厚朴行氣除滿、燥濕為臣；陳皮理氣化滯為佐；炙甘草調和諸藥為使。",
         cautions=["陰虛氣滯、脾胃虛弱者不宜", "孕婦慎用"]),
    dict(id="F_LINGGUIZHUGAN", zh="苓桂朮甘湯", en="Ling Gui Zhu Gan Tang (Poria, Cinnamon Twig, Atractylodes and Licorice Decoction)", school=J, source=dict(book="金匱要略", ref="jingui-012-1"),
         classical=dict(lib="library/fangji/jingfang/lingguizhugantang/lingguizhugantang_001.md"), patterns=["SP4"], principle="溫陽化飲、健脾利濕",
         herbs=[("茯苓", "君", 12), ("桂枝", "臣", 9), ("白朮", "佐", 6), ("炙甘草", "使", 6)],
         core=["S_CHEST_OPPRESSION", "S_HEAD_DIZZY", "S_PHLEGM_COPIOUS", "T_COAT_SLIPPERY", "P_SLIPPERY"],
         fangyi="茯苓健脾滲濕、化飲為君；桂枝溫陽化氣、平沖降逆為臣；白朮健脾燥濕為佐；炙甘草益氣和中、調和諸藥為使。《金匱》言「病痰飲者，當以溫藥和之」。",
         cautions=["陰虛火旺、痰熱者不宜", "孕婦慎用桂枝"]),
    dict(id="F_SANREN", zh="三仁湯", en="Sanren Tang (Three Kernels Decoction)", school=S, source=dict(book="溫病條辨", ref="上焦篇", prefix="526", heading="三仁汤"),
         patterns=["SP5"], principle="宣暢氣機、清利濕熱",
         herbs=[("杏仁", "君", 15), ("白豆蔻", "君", 6), ("薏苡仁", "君", 18), ("滑石", "臣", 18), ("通草", "臣", 6), ("竹葉", "臣", 6), ("厚朴", "佐", 6), ("半夏", "佐", 15)],
         core=["S_FEVER_UNEVEN", "S_BODY_HEAVY", "S_EPIGASTRIC_FULLNESS", "S_STICKY_MOUTH", "T_COAT_YELLOW_GREASY"],
         fangyi="杏仁宣利上焦肺氣，白蔻仁芳香化濕、行氣寬中，薏苡仁甘淡滲濕利下，三者共為君，宣上、暢中、滲下；滑石、通草、竹葉清熱利濕為臣；厚朴、半夏行氣燥濕、散滿消痞為佐。",
         cautions=["陰虛津傷、無濕熱者忌用", "孕婦慎用（薏苡仁、滑石、半夏）", "不宜與烏頭類同用（含半夏）"]),
    dict(id="F_GANLU", zh="甘露消毒丹", en="Ganlu Xiaodu Dan (Sweet Dew Toxin-Removing Pill)", school=S, source=dict(book="溫熱經緯", ref="卷五", prefix="543", heading="甘露消毒丹"),
         patterns=["SP5"], principle="利濕化濁、清熱解毒",
         herbs=[("滑石", "君", 15), ("茵陳", "君", 11), ("黃芩", "君", 10), ("石菖蒲", "臣", 6), ("川貝母", "臣", 5), ("木通", "臣", 5), ("藿香", "佐", 4),
                ("連翹", "佐", 4), ("白豆蔻", "佐", 4), ("薄荷", "佐", 4), ("射干", "佐", 4)],
         core=["S_STICKY_MOUTH", "S_BITTER_MOUTH", "S_URINE_YELLOW_SCANTY", "S_BODY_HEAVY", "T_COAT_YELLOW_GREASY"],
         fangyi="滑石利水清熱、茵陳清熱利濕退黃、黃芩清熱燥濕共為君；石菖蒲、川貝母、木通化濕化痰、導熱下行為臣；藿香、白豆蔻、薄荷芳香化濁，連翹、射干清熱解毒利咽為佐。",
         cautions=["原方「木通」須用川木通或通草，絕不可用含馬兜鈴酸的關木通", "寒濕證、陰虛者不宜", "孕婦慎用"]),
    dict(id="F_YIWEI", zh="益胃湯", en="Yiwei Tang (Benefit the Stomach Decoction)", school=S, source=dict(book="溫病條辨", ref="中焦篇", prefix="526", heading="益胃汤"),
         patterns=["SP6"], principle="養陰益胃",
         herbs=[("生地黃", "君", 15), ("麥冬", "君", 15), ("沙參", "臣", 9), ("玉竹", "臣", 4.5), ("冰糖", "佐", 3)],
         core=["S_DRY_MOUTH_THROAT", "S_HUNGER_NO_EAT", "S_EPIGASTRIC_BURNING", "T_CRACKS_CENTER"],
         fangyi="生地黃、麥冬甘寒養陰、清熱生津為君；沙參、玉竹養陰生津、益胃為臣；冰糖濡養肺胃、調和諸藥為佐。",
         cautions=["脾胃虛寒、濕盛、痰濕者忌用", "糖尿病者慎用冰糖"]),
    dict(id="F_XIAOYAO", zh="逍遙散", en="Xiaoyao San (Free and Easy Wanderer Powder)", school=S, source=dict(book="太平惠民和劑局方", ref="卷九", prefix="059", heading="逍遥散"),
         patterns=["LV1"], principle="疏肝解鬱、養血健脾",
         herbs=[("柴胡", "君", 9), ("當歸", "臣", 9), ("芍藥", "臣", 9), ("白朮", "佐", 9), ("茯苓", "佐", 9), ("炙甘草", "使", 4.5), ("薄荷", "佐", 3), ("生薑", "佐", 3, "煨")],
         core=["S_DEPRESSED", "S_SIGHING", "S_HYPOCHONDRIAC_DISTENSION", "S_BREAST_DISTENSION", "S_MENSES_IRREGULAR", "P_WIRY"],
         fangyi="柴胡疏肝解鬱為君；當歸、白芍養血柔肝為臣，與柴胡相配補肝體而助肝用；白朮、茯苓健脾祛濕，薄荷疏散鬱遏之氣、透達肝經，煨薑溫胃和中為佐；炙甘草調和諸藥為使。",
         cautions=["肝陽上亢、陰虛火旺者慎用", "孕婦慎用（含當歸）", "服藥期間宜情緒舒暢"],
         modifications=[
             dict(id="M_XIAOYAO_DANZHI", result="丹梔逍遙散", add=[("牡丹皮", "佐", 6), ("梔子", "佐", 6)], remove=[], when=["S_IRRITABLE", "S_BITTER_MOUTH", "T_EDGE_RED"], source=dict(book="醫方集解", prefix="087", heading="逍遥散")),
             dict(id="M_XIAOYAO_HEI", result="黑逍遙散", add=[("熟地黃", "佐", 12)], remove=[], when=["S_BLURRED_VISION", "S_MENSES_SCANTY_PALE"], source=dict(book="醫宗已任編", prefix="624", heading="黑逍遥")),
         ]),
    dict(id="F_CHAIHUSHUGAN", zh="柴胡疏肝散", en="Chaihu Shugan San (Bupleurum Liver-Soothing Powder)", school=S, source=dict(book="景岳全書", ref="卷五十六", prefix="637", heading="柴胡疏肝散"),
         patterns=["LV1", "LV4"], principle="疏肝理氣、活血止痛",
         herbs=[("柴胡", "君", 6), ("香附", "臣", 4.5), ("川芎", "臣", 4.5), ("陳皮", "佐", 6), ("枳殼", "佐", 4.5), ("芍藥", "佐", 4.5), ("炙甘草", "使", 1.5)],
         core=["S_HYPOCHONDRIAC_DISTENSION", "S_EPIGASTRIC_PAIN", "S_BELCHING", "S_EMOTION_TRIGGERED", "P_WIRY"],
         fangyi="柴胡疏肝解鬱為君；香附理氣疏肝止痛，川芎活血行氣止痛為臣；陳皮、枳殼理氣行滯，芍藥、甘草養血柔肝、緩急止痛為佐使。",
         cautions=["陰虛火旺、脅痛由肝血不足者不宜", "孕婦慎用（川芎、枳殼）"]),
    dict(id="F_YUEJU", zh="越鞠丸", en="Yueju Wan (Escape Restraint Pill)", school=S, source=dict(book="丹溪心法", ref="卷三", prefix="570", heading="越鞠丸"),
         patterns=["LV1"], principle="行氣解鬱（氣血痰火濕食六鬱）",
         herbs=[("香附", "君", 9), ("川芎", "臣", 9), ("蒼朮", "臣", 9), ("神曲", "佐", 9), ("梔子", "佐", 9)],
         core=["S_CHEST_OPPRESSION", "S_EPIGASTRIC_FULLNESS", "S_POSTPRANDIAL_BLOAT", "S_DEPRESSED"],
         fangyi="香附行氣解氣鬱為君；川芎活血行氣以解血鬱，蒼朮燥濕運脾以解濕鬱，神曲消食和胃以解食鬱，梔子清熱瀉火以解火鬱；痰鬱乃氣滯濕聚而成，諸鬱得解而痰鬱隨之消除。",
         cautions=["虛證鬱滯者不宜單用", "孕婦慎用（川芎）"]),
    dict(id="F_LONGDAN", zh="龍膽瀉肝湯", en="Longdan Xiegan Tang (Gentian Liver-Draining Decoction)", school=S, source=dict(book="醫方集解", ref="瀉火之劑", prefix="087", heading="龙胆泻肝汤"),
         patterns=["LV2"], principle="清瀉肝膽實火、清利肝經濕熱",
         herbs=[("龍膽草", "君", 6), ("黃芩", "臣", 9), ("梔子", "臣", 9), ("澤瀉", "佐", 12), ("木通", "佐", 9), ("車前子", "佐", 9), ("當歸", "佐", 3),
                ("生地黃", "佐", 9), ("柴胡", "使", 6), ("甘草", "使", 6)],
         core=["S_HEAD_DISTENDING", "S_IRRITABLE", "S_BITTER_MOUTH", "S_TINNITUS_HIGH_LOUD", "T_EDGE_RED", "P_WIRY", "P_RAPID"],
         fangyi="龍膽草大苦大寒、瀉肝膽實火並利肝經濕熱為君；黃芩、梔子苦寒瀉火為臣；澤瀉、木通、車前子清利濕熱，當歸、生地養血滋陰以顧護肝陰為佐；柴胡疏肝引經，甘草調和諸藥為使。",
         cautions=["苦寒峻烈易傷脾胃，不宜久服", "脾胃虛寒、陰虛陽亢者忌用", "木通須用川木通，不可用關木通", "孕婦慎用"]),
    dict(id="F_SIWU", zh="四物湯", en="Siwu Tang (Four Substances Decoction)", school=S, source=dict(book="太平惠民和劑局方", ref="卷九", prefix="059", heading="四物汤"),
         patterns=["LV3"], principle="補血調血",
         herbs=[("熟地黃", "君", 12), ("當歸", "臣", 10), ("芍藥", "佐", 12), ("川芎", "使", 8)],
         core=["S_BLURRED_VISION", "S_NAIL_BRITTLE", "S_MENSES_SCANTY_PALE", "S_HEAD_DIZZY", "T_BODY_PALE"],
         fangyi="熟地黃滋陰養血為君；當歸補血養肝、和血調經為臣；白芍養血柔肝和營為佐；川芎活血行氣、調暢氣血為使，使補而不滯。",
         cautions=["脾胃虛弱、食少便溏者慎用", "孕婦慎用（川芎、當歸）"],
         modifications=[dict(id="M_SIWU_TAOHONG", result="桃紅四物湯", add=[("桃仁", "佐", 9), ("紅花", "佐", 6)], remove=[], when=["S_MENSES_CLOTS_DARK", "S_DYSMENORRHEA"], source=dict(book="醫宗金鑑", prefix="575", heading="桃红四物汤"))]),
    dict(id="F_SUANZAOREN", zh="酸棗仁湯", en="Suanzaoren Tang (Sour Jujube Seed Decoction)", school=J, source=dict(book="金匱要略", ref="jingui-006-1"),
         classical=dict(raw="raw/jingui/jingui_06.txt", heading="酸枣仁汤方"), patterns=["LV3"], principle="養血安神、清熱除煩",
         herbs=[("酸棗仁", "君", 15), ("茯苓", "臣", 6), ("知母", "佐", 6), ("川芎", "佐", 6), ("甘草", "使", 3)],
         core=["S_INSOMNIA_MAINT", "S_RESTLESS_NO_SLEEP", "S_DREAM_MANY", "S_BLURRED_VISION", "P_THIN"],
         fangyi="酸棗仁養血補肝、寧心安神為君；茯苓寧心安神為臣；知母滋陰清熱、除煩安神，川芎調血疏肝為佐；甘草和中緩急、調和諸藥為使。",
         cautions=["孕婦慎用（川芎）", "有實邪鬱火者慎用酸棗仁", "服藥期間避免咖啡、濃茶"]),
    dict(id="F_GUIPI", zh="歸脾湯", en="Guipi Tang (Restore the Spleen Decoction)", school=S, source=dict(book="嚴氏濟生方", ref="卷四", prefix="077", heading="归脾汤"),
         source_note="《嚴氏濟生方》原方無當歸、遠志（後世薛己《校注婦人良方》加入）；本表採通行方。",
         patterns=["HT1"], principle="益氣補血、健脾養心",
         herbs=[("黃耆", "君", 12), ("龍眼肉", "君", 12), ("人參", "臣", 6), ("白朮", "臣", 9), ("當歸", "臣", 9), ("酸棗仁", "臣", 12), ("茯神", "臣", 9),
                ("遠志", "臣", 6), ("木香", "佐", 6), ("炙甘草", "使", 3)],
         core=["S_PALPITATION", "S_FORGETFUL", "S_INSOMNIA_MAINT", "S_FATIGUE", "S_FACE_SALLOW", "T_BODY_PALE"],
         fangyi="黃耆補脾益氣、龍眼肉補益心脾、養血安神共為君；人參、白朮助黃耆補脾益氣，當歸助龍眼肉養血，酸棗仁、茯神、遠志寧心安神為臣；木香理氣醒脾、使補而不滯為佐；炙甘草調和諸藥為使。",
         cautions=["陰虛火旺、痰濕內盛者不宜", "孕婦慎用（當歸）", "外感發熱者暫停"]),
    dict(id="F_HUANGLIANEJIAO", zh="黃連阿膠湯", en="Huanglian Ejiao Tang (Coptis and Donkey-Hide Gelatin Decoction)", school=J, source=dict(book="傷寒論", ref="shanghan-303"),
         classical=dict(lib="library/fangji/jingfang/huanglianejiaotang/huanglianejiaotang_001.md"), patterns=["HT2"], principle="滋陰降火、交通心腎",
         herbs=[("黃連", "君", 12), ("阿膠", "君", 9), ("黃芩", "臣", 6), ("芍藥", "臣", 6), ("雞子黃", "佐", 2)],
         core=["S_RESTLESS_NO_SLEEP", "S_PALPITATION", "S_HEAT_PALMS_SOLES", "T_TIP_RED", "P_RAPID"],
         fangyi="黃連清心火、阿膠滋腎陰，水火既濟為君；黃芩助黃連清火，芍藥助阿膠滋陰為臣；雞子黃養心滋陰、安神除煩為佐。",
         cautions=["脾胃虛寒、泄瀉者忌用", "苦寒藥不宜久服", "蛋類過敏者忌用雞子黃"]),
    dict(id="F_TIANWANG", zh="天王補心丹", en="Tianwang Buxin Dan (Celestial Emperor Heart-Supplementing Elixir)", school=S, source=dict(book="醫方集解", ref="補養之劑", prefix="087", heading="天王补心丹"),
         patterns=["HT2"], principle="滋陰清熱、養血安神",
         herbs=[("生地黃", "君", 12), ("天冬", "臣", 6), ("麥冬", "臣", 6), ("酸棗仁", "臣", 6), ("柏子仁", "臣", 6), ("當歸", "佐", 6), ("玄參", "佐", 3),
                ("丹參", "佐", 3), ("茯苓", "佐", 3), ("人參", "佐", 3), ("五味子", "佐", 3), ("遠志", "佐", 3), ("桔梗", "使", 3)],
         core=["S_RESTLESS_NO_SLEEP", "S_FORGETFUL", "S_HEAT_PALMS_SOLES", "S_NIGHT_SWEAT", "T_TIP_RED", "P_THIN"],
         fangyi="重用生地黃滋陰清熱為君；天冬、麥冬、酸棗仁、柏子仁滋陰養血、養心安神為臣；玄參、當歸、丹參、茯苓、人參、五味子、遠志補氣血、寧心神為佐；桔梗載藥上行為使。原方以朱砂為衣，因含汞，本專案配方不收朱砂。",
         cautions=["原方朱砂為衣，已略去（含汞）", "脾胃虛寒、痰濕者慎用（滋膩藥多）", "不宜與藜蘆同用（含人參、玄參、丹參）"]),
    dict(id="F_WENDAN", zh="溫膽湯", en="Wendan Tang (Gallbladder-Warming Decoction)", school=S, source=dict(book="三因極一病證方論", ref="卷九", prefix="558", heading="温胆汤"),
         patterns=["HT3"], principle="理氣化痰、清膽和胃",
         herbs=[("半夏", "君", 6), ("竹茹", "臣", 6), ("枳實", "佐", 6), ("陳皮", "佐", 9), ("茯苓", "佐", 4.5), ("生薑", "佐", 5), ("大棗", "佐", 3), ("炙甘草", "使", 3)],
         core=["S_STARTLE", "S_INSOMNIA_ONSET", "S_PHLEGM_COPIOUS", "S_BITTER_MOUTH", "T_COAT_YELLOW_GREASY", "P_SLIPPERY"],
         fangyi="半夏燥濕化痰、和胃止嘔為君；竹茹清熱化痰、除煩止嘔為臣；枳實、陳皮理氣化痰，茯苓健脾滲濕，生薑、大棗和中為佐；炙甘草調和諸藥為使。",
         cautions=["陰虛燥咳者不宜", "孕婦慎用（半夏、枳實）"]),
    dict(id="F_YUPINGFENG", zh="玉屏風散", en="Yupingfeng San (Jade Windscreen Powder)", school=S, source=dict(book="丹溪心法", ref="卷三", prefix="570", heading="玉屏风散"),
         patterns=["LG1"], principle="益氣固表止汗",
         herbs=[("黃耆", "君", 18), ("白朮", "臣", 12), ("防風", "佐", 6)],
         core=["S_SPONTANEOUS_SWEAT", "S_AVERSION_WIND", "S_EASY_COLD", "S_SHORT_BREATH"],
         fangyi="黃耆益氣固表止汗為君；白朮健脾益氣、助黃耆固表為臣；防風祛風走表，與黃耆相配固表而不留邪、散風而不傷正為佐使。",
         cautions=["外感風邪、表實無汗者不宜", "陰虛盜汗者不宜"]),
    dict(id="F_MAIMENDONG", zh="麥門冬湯", en="Maimendong Tang (Ophiopogon Decoction)", school=J, source=dict(book="金匱要略", ref="jingui-007-1"),
         classical=dict(raw="raw/jingui/jingui_07.txt", heading="麦门冬汤方"), patterns=["LG2"], principle="清養肺胃、降逆下氣",
         herbs=[("麥冬", "君", 42), ("半夏", "臣", 6), ("人參", "佐", 9), ("粳米", "佐", 6), ("大棗", "佐", 4), ("甘草", "使", 6)],
         core=["S_COUGH_DRY", "S_DRY_MOUTH_THROAT", "S_DRY_THROAT", "T_COAT_PEELED_ALL", "P_THIN"],
         fangyi="重用麥冬養陰生津、滋養肺胃、清虛火為君；半夏降逆下氣、化痰，用量甚輕且與大量麥冬相伍，不燥不傷陰為臣；人參、粳米、大棗益氣養胃、使胃得養而肺氣充為佐；甘草潤肺利咽、調和諸藥為使。",
         cautions=["痰濕咳嗽者不宜", "半夏須炮製", "不宜與藜蘆、五靈脂同用（含人參）"]),
    dict(id="F_SHASHEN", zh="沙參麥冬湯", en="Shashen Maidong Tang (Glehnia and Ophiopogon Decoction)", school=S, source=dict(book="溫病條辨", ref="上焦篇", prefix="526", heading="沙参麦冬汤"),
         patterns=["LG2"], principle="甘寒生津、清養肺胃",
         herbs=[("沙參", "君", 9), ("麥冬", "君", 9), ("玉竹", "臣", 6), ("天花粉", "臣", 4.5), ("桑葉", "佐", 4.5), ("白扁豆", "佐", 4.5), ("甘草", "使", 3)],
         core=["S_COUGH_DRY", "S_DRY_MOUTH_THROAT", "S_HOARSE", "T_BODY_RED", "P_THIN"],
         fangyi="沙參、麥冬甘寒養陰、清肺潤燥為君；玉竹、天花粉助君藥生津養陰為臣；桑葉輕宣燥熱，白扁豆健脾和中為佐；甘草調和諸藥為使。",
         cautions=["外感風寒咳嗽、痰濕者不宜", "不宜與烏頭類同用（含天花粉）", "不宜與藜蘆同用（含沙參）"]),
    dict(id="F_LIUWEI", zh="六味地黃丸", en="Liuwei Dihuang Wan (Six-Ingredient Rehmannia Pill)", school=S, source=dict(book="小兒藥證直訣", ref="卷下", prefix="133", heading="地黄丸"),
         patterns=["KD1"], principle="滋陰補腎",
         herbs=[("熟地黃", "君", 24), ("山茱萸", "臣", 12), ("山藥", "臣", 12), ("澤瀉", "佐", 9), ("牡丹皮", "佐", 9), ("茯苓", "佐", 9)],
         core=["S_LOW_BACK_SORE", "S_HEAT_PALMS_SOLES", "S_TINNITUS_THIN", "S_NIGHT_SWEAT", "T_ROOT_COAT_PEELED", "P_THIN"],
         fangyi="重用熟地黃滋陰補腎、填精益髓為君；山茱萸養肝澀精，山藥補脾固精為臣，三陰並補；澤瀉利濕泄濁、牡丹皮清瀉肝火、茯苓淡滲脾濕為佐，三瀉以制三補之滯。",
         cautions=["脾虛便溏、食少者慎用（滋膩）", "孕婦慎用牡丹皮", "感冒發熱期間暫停"],
         modifications=[
             dict(id="M_LIUWEI_ZHIBAI", result="知柏地黃丸", add=[("知母", "佐", 6), ("黃柏", "佐", 6)], remove=[], when=["S_HEAT_PALMS_SOLES", "S_NIGHT_SWEAT", "S_TIDAL_FEVER"], source=dict(book="醫方考", prefix="072", heading="知柏")),
             dict(id="M_LIUWEI_QIJU", result="杞菊地黃丸", add=[("枸杞子", "佐", 9), ("菊花", "佐", 9)], remove=[], when=["S_BLURRED_VISION", "S_DRY_EYES"], source=dict(book="醫級", prefix="", heading="杞菊")),
         ]),
    dict(id="F_SHENQI", zh="腎氣丸", en="Shenqi Wan (Kidney Qi Pill)", school=J, source=dict(book="金匱要略", ref="jingui-006-2"),
         classical=dict(lib="library/fangji/jingfang/shenqiwan/shenqiwan_001.md"), patterns=["KD2"], principle="補腎助陽、陰中求陽",
         herbs=[("附子", "君", 3), ("桂枝", "君", 3), ("乾地黃", "臣", 24), ("山茱萸", "臣", 12), ("山藥", "臣", 12), ("澤瀉", "佐", 9), ("茯苓", "佐", 9), ("牡丹皮", "佐", 9)],
         core=["S_LOW_BACK_COLD", "S_FEAR_COLD", "S_FREQUENT_NOCTURIA", "S_EDEMA", "T_BODY_PALE_SWOLLEN", "P_SINK"],
         fangyi="附子、桂枝（後世或用肉桂）溫補腎陽、鼓舞腎氣為君，取「少火生氣」；乾地黃、山茱萸、山藥滋補腎陰、陰中求陽為臣；澤瀉、茯苓利水滲濕，牡丹皮清泄肝火為佐。",
         cautions=["含附子：有毒，孕婦禁用，須久煎並由醫師處方", "陰虛火旺者忌用", "不宜與半夏、瓜蔞、貝母、白蘞、白及同用"]),
    dict(id="F_YOUGUI", zh="右歸丸", en="Yougui Wan (Restore the Right [Kidney] Pill)", school=S, source=dict(book="景岳全書", ref="新方八陣·補陣", prefix="637", heading="右归丸"),
         patterns=["KD2"], principle="溫補腎陽、填精益髓",
         herbs=[("附子", "君", 6), ("肉桂", "君", 6), ("鹿角膠", "君", 12), ("熟地黃", "臣", 24), ("山藥", "臣", 12), ("山茱萸", "臣", 9), ("枸杞子", "臣", 12),
                ("菟絲子", "佐", 12), ("杜仲", "佐", 12), ("當歸", "佐", 9)],
         core=["S_LOW_BACK_COLD", "S_FEAR_COLD", "S_FREQUENT_NOCTURIA", "S_SPIRIT_WITHDRAWN", "P_SINK"],
         fangyi="附子、肉桂溫補腎陽，鹿角膠溫腎陽、益精血共為君；熟地黃、山藥、山茱萸、枸杞子滋陰益腎、養肝補脾，陰中求陽為臣；菟絲子、杜仲補肝腎、強腰膝，當歸養血和血為佐。",
         cautions=["含附子、肉桂：孕婦禁用附子，須由醫師處方", "陰虛火旺、濕熱者忌用", "感冒期間暫停"]),
    dict(id="F_BAZHEN", zh="八珍湯", en="Bazhen Tang (Eight-Treasure Decoction)", school=S, source=dict(book="正體類要", ref="卷下", prefix="247", heading="八珍汤"),
         patterns=["QB1"], principle="益氣補血",
         herbs=[("人參", "君", 10), ("熟地黃", "君", 10), ("白朮", "臣", 10), ("茯苓", "臣", 10), ("當歸", "臣", 10), ("芍藥", "臣", 10), ("川芎", "佐", 5),
                ("炙甘草", "使", 5), ("生薑", "使", 3), ("大棗", "使", 6)],
         core=["S_FATIGUE", "S_HEAD_DIZZY", "S_PALPITATION", "S_FACE_PALE", "T_BODY_PALE", "P_THIN"],
         fangyi="人參、熟地黃益氣養血共為君；白朮、茯苓健脾，當歸、白芍養血為臣；川芎活血行氣使補而不滯為佐；炙甘草、生薑、大棗和中調營為使。即四君子湯合四物湯。",
         cautions=["外感發熱、實證者不宜", "脾胃虛弱、食少便溏者慎用（滋膩）", "孕婦慎用（當歸、川芎）"]),
    dict(id="F_XUEFU", zh="血府逐瘀湯", en="Xuefu Zhuyu Tang (Drive Out Stasis in the Mansion of Blood Decoction)", school=S, source=dict(book="醫林改錯", ref="卷上", prefix="204", heading="血府逐瘀汤"),
         patterns=["QB2"], principle="活血化瘀、行氣止痛",
         herbs=[("桃仁", "君", 12), ("紅花", "君", 9), ("赤芍", "臣", 6), ("川芎", "臣", 4.5), ("牛膝", "臣", 9), ("當歸", "佐", 9), ("生地黃", "佐", 9),
                ("柴胡", "佐", 3), ("枳殼", "佐", 6), ("桔梗", "使", 4.5), ("甘草", "使", 6)],
         core=["S_STABBING_PAIN_FIXED", "S_PAIN_NIGHT_WORSE", "S_MENSES_CLOTS_DARK", "T_ECCHYMOSIS", "P_CHOPPY"],
         fangyi="桃仁、紅花活血化瘀為君；赤芍、川芎助君藥活血，牛膝祛瘀通脈、引血下行為臣；生地黃、當歸養血益陰、使祛瘀而不傷正，柴胡、枳殼疏肝理氣，桔梗開肺氣、載藥上行為佐使；甘草調和諸藥。",
         cautions=["孕婦及月經過多者禁用", "服用抗凝血藥或有出血傾向者禁用", "無瘀血者不宜"]),
    dict(id="F_XIAOCHAIHU", zh="小柴胡湯", en="Xiao Chaihu Tang (Minor Bupleurum Decoction)", school=J, source=dict(book="傷寒論", ref="shanghan-096"),
         classical=dict(lib="library/fangji/jingfang/xiaochaihutang/xiaochaihutang_001.md"), patterns=[], mvp=False, principle="和解少陽",
         herbs=[("柴胡", "君", 24), ("黃芩", "臣", 9), ("半夏", "佐", 9), ("人參", "佐", 9), ("炙甘草", "使", 9), ("生薑", "佐", 9), ("大棗", "佐", 12)],
         core=["S_ALTERNATING_CHILLS_FEVER", "S_HYPOCHONDRIAC_DISTENSION", "S_BITTER_MOUTH", "S_NAUSEA"],
         fangyi="柴胡透泄少陽之邪、疏達經氣為君；黃芩清泄少陽之熱為臣；半夏、生薑和胃降逆，人參、炙甘草、大棗扶正祛邪為佐使。少陽往來寒熱屬應就醫的外感，不列入 MVP 自助推薦，僅供學習。",
         cautions=["往來寒熱屬外感症狀，應就醫評估", "僅供學習顯示，不作推薦"]),
]
