"""The 23-pattern MVP library (curated draft; every row awaits practitioner review).

weights  : positive evidence, 1 = minor, 2 = important, 3 = specific/cardinal
against  : negative evidence (reduces the pattern), same scale
required : at least one of these must be present, else the pattern score is halved (SOP §8.3)
elements : 證素 decomposition — (location, nature) pairs; the panel projection is applied to these
cites    : ids in data/citations.json
formulas : ids in data/formulas.json (filled/validated at build time)
Tongue/pulse weights are included; the engine applies the data-quality coefficient (pulse is optional
self-reported input and is down-weighted).
"""

P = lambda **kw: kw  # noqa: E731  (tiny readability helper)

PATTERNS = [
    # ── external ────────────────────────────────────────────────────────────
    dict(id="EX1", zh="風寒束表（太陽傷寒）", en="Wind-cold fettering the exterior (taiyang cold damage)", group="external",
         elements=[("表", "風"), ("表", "寒")], principle="辛溫解表、發汗", formulas=["F_MAHUANG"],
         weights=dict(S_AVERSION_COLD=3, S_NO_SWEAT=3, S_FEVER=2, S_BODY_ACHE=2, S_HEADACHE=2, S_RUNNY_NOSE_CLEAR=2,
                      S_NASAL_CONGESTION=1, S_NO_THIRST=1, T_COAT_THIN_WHITE=1, P_FLOAT=2, P_TIGHT=2),
         against=dict(S_SPONTANEOUS_SWEAT=2, S_THIRST_COLD_DRINK=2, S_SORE_THROAT=1, T_BODY_RED=1),
         required=["S_AVERSION_COLD"], cites=["shanghan-003", "shanghan-035"],
         tongue_pulse="苔薄白；脈浮緊"),
    dict(id="EX2", zh="太陽中風（表虛）", en="Taiyang wind strike (exterior deficiency)", group="external",
         elements=[("表", "風")], principle="解肌發表、調和營衛", formulas=["F_GUIZHI"],
         weights=dict(S_FEVER=2, S_SPONTANEOUS_SWEAT=3, S_AVERSION_WIND=3, S_AVERSION_COLD=1, S_HEADACHE=1,
                      S_NASAL_CONGESTION=1, T_COAT_THIN_WHITE=1, P_FLOAT=2, P_MODERATE=2),
         against=dict(S_NO_SWEAT=3, S_THIRST_COLD_DRINK=2),
         required=["S_AVERSION_WIND", "S_SPONTANEOUS_SWEAT"], cites=["shanghan-002"],
         tongue_pulse="苔薄白；脈浮緩"),
    dict(id="EX3", zh="風熱犯表", en="Wind-heat invading the exterior", group="external",
         elements=[("表", "風"), ("表", "火")], principle="辛涼解表", formulas=["F_YINQIAO", "F_SANGJU"],
         weights=dict(S_FEVER=3, S_AVERSION_COLD=1, S_SORE_THROAT=3, S_DRY_THROAT=1, S_THIRST_LIGHT=2,
                      S_COUGH_PHLEGM_YELLOW=2, S_HEADACHE=1, S_NASAL_CONGESTION=1, T_TIP_RED=2, T_EDGE_RED=2,
                      T_RED_DOTS_TIP=2, T_COAT_YELLOW=1, P_FLOAT=2, P_RAPID=2),
         against=dict(S_NO_THIRST=2, T_COAT_WHITE_GREASY=1),
         required=["S_FEVER", "S_SORE_THROAT"], cites=["shanghan-006"],
         tongue_pulse="舌邊尖紅，苔薄黃；脈浮數"),
    dict(id="EX4", zh="營衛不和", en="Disharmony of nutrient and defensive qi", group="external",
         elements=[("表", "氣虛")], principle="調和營衛", formulas=["F_GUIZHI"],
         weights=dict(S_SPONTANEOUS_SWEAT=3, S_AVERSION_WIND=3, S_EASY_COLD=2, S_FATIGUE=1, T_COAT_THIN_WHITE=1,
                      P_MODERATE=1, P_FLOAT=1),
         against=dict(S_NO_SWEAT=2, S_THIRST_COLD_DRINK=1, S_NIGHT_SWEAT=1),
         required=["S_SPONTANEOUS_SWEAT"], cites=["shanghan-053"],
         tongue_pulse="苔薄白；脈緩"),
    # ── spleen / stomach ───────────────────────────────────────────────────
    dict(id="SP1", zh="脾氣虛", en="Spleen qi deficiency", group="spleen-stomach",
         elements=[("脾", "氣虛")], principle="益氣健脾", formulas=["F_SIJUNZI", "F_SHENLING"],
         weights=dict(S_POOR_APPETITE=3, S_POSTPRANDIAL_BLOAT=3, S_LOOSE_STOOL=3, S_FATIGUE=2, S_LAZY_SPEAK=2,
                      S_FACE_SALLOW=1, S_EDEMA=1, S_BLAND_MOUTH=1, T_BODY_PALE=2, T_TOOTHMARK_EDGE=2,
                      T_BODY_PALE_SWOLLEN=1, T_COAT_THIN_WHITE=1, P_DEFICIENT=1, P_SOFT=1),
         against=dict(S_THIRST_COLD_DRINK=2, S_CONSTIPATION=2, S_ABD_REFUSE_PRESS=2, T_COAT_YELLOW_GREASY=1),
         required=["S_POOR_APPETITE", "S_POSTPRANDIAL_BLOAT", "S_LOOSE_STOOL"], cites=["lingshu-008-1"],
         tongue_pulse="舌淡苔白，常胖有齒痕；脈緩弱"),
    dict(id="SP2", zh="脾陽虛（脾胃虛寒）", en="Spleen yang deficiency (spleen-stomach cold)", group="spleen-stomach",
         elements=[("脾", "陽虛"), ("脾", "寒")], principle="溫中健脾", formulas=["F_LIZHONG"],
         weights=dict(S_ABD_PAIN_PREFER_WARM_PRESS=3, S_FEAR_COLD=3, S_COLD_LIMBS=2, S_LOOSE_STOOL=3, S_UNDIGESTED_STOOL=2,
                      S_BLAND_MOUTH=2, S_NO_THIRST=1, S_PREFER_HOT_FOOD=2, S_POOR_APPETITE=2, S_POSTPRANDIAL_BLOAT=1,
                      S_EDEMA=1, T_BODY_PALE_SWOLLEN=2, T_COAT_SLIPPERY=2, T_TOOTHMARK_EDGE=1, P_SINK=2, P_SLOW=2,
                      P_DEFICIENT=1),
         against=dict(S_THIRST_COLD_DRINK=3, S_FEAR_HEAT=2, S_CONSTIPATION=2, T_BODY_RED=2),
         required=["S_ABD_PAIN_PREFER_WARM_PRESS", "S_FEAR_COLD"], cites=["shanghan-273", "shanghan-386", "jingui-010-2"],
         tongue_pulse="舌淡胖苔白滑；脈沉遲"),
    dict(id="SP3", zh="中氣下陷", en="Sinking of middle qi", group="spleen-stomach",
         elements=[("脾", "氣虛")], principle="補中益氣、升陽舉陷", formulas=["F_BUZHONG"],
         weights=dict(S_PROLAPSE_SENSATION=3, S_FATIGUE=2, S_SHORT_BREATH=2, S_LOOSE_STOOL=1, S_POSTPRANDIAL_BLOAT=2,
                      S_LAZY_SPEAK=2, S_POOR_APPETITE=1, T_BODY_PALE=1, T_COAT_THIN_WHITE=1, P_DEFICIENT=1, P_SOFT=1),
         against=dict(S_THIRST_COLD_DRINK=1, S_ABD_REFUSE_PRESS=1),
         required=["S_PROLAPSE_SENSATION"], cites=[],
         tongue_pulse="舌淡；脈弱"),
    dict(id="SP4", zh="痰濕內阻", en="Phlegm-dampness obstruction", group="spleen-stomach",
         elements=[("脾", "濕"), ("脾", "痰")], principle="燥濕化痰、理氣和中", formulas=["F_ERCHEN", "F_PINGWEI", "F_LINGGUIZHUGAN"],
         weights=dict(S_BODY_HEAVY=3, S_PHLEGM_COPIOUS=3, S_CHEST_OPPRESSION=2, S_EPIGASTRIC_FULLNESS=2, S_HEAD_HEAVY=2,
                      S_STICKY_MOUTH=2, S_STICKY_STOOL=1, S_POOR_APPETITE=1, S_NAUSEA=1, S_THIRST_NO_DRINK=1,
                      T_BODY_PALE_SWOLLEN=1, T_COAT_WHITE_GREASY=3, T_TOOTHMARK_EDGE=1, T_CENTER_COAT_THICK=1, P_SLIPPERY=2),
         against=dict(S_THIRST_COLD_DRINK=1, T_COAT_PEELED_ALL=3, S_DRY_MOUTH_THROAT=2, T_COAT_DRY=2),
         required=["S_BODY_HEAVY", "S_PHLEGM_COPIOUS", "T_COAT_WHITE_GREASY"], cites=["jingui-012-1"],
         tongue_pulse="舌胖苔膩；脈滑"),
    dict(id="SP5", zh="濕熱蘊結", en="Damp-heat accumulation", group="spleen-stomach",
         elements=[("脾", "濕"), ("胃", "火")], principle="清熱利濕", formulas=["F_SANREN", "F_GANLU"],
         weights=dict(S_STICKY_MOUTH=2, S_BITTER_MOUTH=2, S_EPIGASTRIC_FULLNESS=2, S_STICKY_STOOL=3, S_URINE_YELLOW_SCANTY=2,
                      S_BODY_HEAVY=2, S_FEVER_UNEVEN=2, S_LEUKORRHEA_YELLOW=1, S_THIRST_NO_DRINK=1, S_NAUSEA=1,
                      T_BODY_RED=1, T_COAT_YELLOW_GREASY=3, T_CENTER_COAT_YELLOW_GREASY=2, T_ROOT_COAT_THICK_GREASY=1,
                      P_SLIPPERY=1, P_RAPID=1),
         against=dict(S_FEAR_COLD=2, S_PREFER_HOT_FOOD=1, T_COAT_WHITE_GREASY=1, T_COAT_PEELED_ALL=2),
         required=["S_STICKY_STOOL", "T_COAT_YELLOW_GREASY"], cites=["suwen-074-5"],
         tongue_pulse="舌紅苔黃膩；脈滑數"),
    dict(id="SP6", zh="胃陰虛", en="Stomach yin deficiency", group="spleen-stomach",
         elements=[("胃", "陰虛")], principle="養陰益胃", formulas=["F_YIWEI"],
         weights=dict(S_EPIGASTRIC_BURNING=3, S_HUNGER_NO_EAT=3, S_DRY_MOUTH_THROAT=3, S_CONSTIPATION=2, S_DRY_RETCH=1,
                      S_THIRST_COLD_DRINK=1, S_HEAT_PALMS_SOLES=1, T_BODY_RED=2, T_CRACKS_CENTER=3, T_COAT_PEELED_ALL=2,
                      T_COAT_DRY=1, T_CENTER_COAT_PEELED=2, P_THIN=1, P_RAPID=1),
         against=dict(T_COAT_WHITE_GREASY=2, S_LOOSE_STOOL=1, S_BODY_HEAVY=1),
         required=["S_DRY_MOUTH_THROAT", "S_HUNGER_NO_EAT", "T_CRACKS_CENTER"], cites=[],
         tongue_pulse="舌紅少津；脈細數"),
    # ── liver ──────────────────────────────────────────────────────────────
    dict(id="LV1", zh="肝氣鬱結", en="Liver qi stagnation", group="liver",
         elements=[("肝", "氣滯")], principle="疏肝解鬱", formulas=["F_XIAOYAO", "F_CHAIHUSHUGAN", "F_YUEJU"],
         weights=dict(S_DEPRESSED=3, S_SIGHING=3, S_HYPOCHONDRIAC_DISTENSION=3, S_THROAT_FOREIGN=2, S_BREAST_DISTENSION=2,
                      S_CHEST_OPPRESSION=1, S_MENSES_IRREGULAR=1, S_PAIN_DISTENDING=2, S_PAIN_WANDERING=1, S_IRRITABLE=1,
                      S_BELCHING=1, T_COAT_THIN_WHITE=1, T_EDGE_RED=1, P_WIRY=3),
         against=dict(S_ABD_PREFER_PRESS=1),
         required=["S_SIGHING", "S_HYPOCHONDRIAC_DISTENSION", "S_DEPRESSED"], cites=["suwen-071-2", "suwen-039-2"],
         tongue_pulse="苔薄白；脈弦"),
    dict(id="LV2", zh="肝火上炎", en="Liver fire flaming upward", group="liver",
         elements=[("肝", "火")], principle="清肝瀉火", formulas=["F_LONGDAN"],
         weights=dict(S_HEAD_DISTENDING=3, S_FACE_RED=2, S_RED_EYES=2, S_IRRITABLE=3, S_BITTER_MOUTH=3, S_TINNITUS_HIGH_LOUD=2,
                      S_CONSTIPATION=1, S_URINE_YELLOW_SCANTY=1, S_HEAD_DIZZY=1, S_THIRST_COLD_DRINK=1, T_BODY_RED=2,
                      T_EDGE_RED=3, T_COAT_YELLOW=2, P_WIRY=2, P_RAPID=2),
         against=dict(S_FEAR_COLD=2, S_FATIGUE=1, T_BODY_PALE=2),
         required=["S_IRRITABLE", "S_BITTER_MOUTH", "T_EDGE_RED"], cites=["suwen-074-6", "suwen-074-7"],
         tongue_pulse="舌紅苔黃；脈弦數"),
    dict(id="LV3", zh="肝血虛", en="Liver blood deficiency", group="liver",
         elements=[("肝", "血虛")], principle="補血養肝（虛煩失眠者養血安神）", formulas=["F_SIWU", "F_SUANZAOREN"],
         weights=dict(S_BLURRED_VISION=3, S_HEAD_DIZZY=2, S_DRY_EYES=2, S_NAIL_BRITTLE=2, S_LIMB_NUMB=2, S_MENSES_SCANTY_PALE=2,
                      S_INSOMNIA_MAINT=1, S_DREAM_MANY=1, S_FACE_PALE=1, S_LIPS_NAILS_PALE=1, T_BODY_PALE=2, P_THIN=2),
         against=dict(S_FACE_RED=1, T_BODY_RED=1, S_THIRST_COLD_DRINK=1),
         required=["S_BLURRED_VISION", "S_NAIL_BRITTLE", "S_MENSES_SCANTY_PALE"], cites=["lingshu-008-2", "suwen-010-2"],
         tongue_pulse="舌淡；脈細"),
    dict(id="LV4", zh="肝胃不和", en="Disharmony between liver and stomach", group="liver",
         elements=[("肝", "氣滯"), ("胃", "氣滯")], principle="疏肝和胃", formulas=["F_CHAIHUSHUGAN"],
         weights=dict(S_EPIGASTRIC_PAIN=3, S_HYPOCHONDRIAC_DISTENSION=2, S_BELCHING=3, S_ACID_REFLUX=2, S_EMOTION_TRIGGERED=2,
                      S_DEPRESSED=1, S_SIGHING=1, S_POOR_APPETITE=1, S_PAIN_DISTENDING=2, T_COAT_THIN_WHITE=1,
                      T_COAT_YELLOW=1, P_WIRY=2),
         against=dict(S_FEAR_COLD=1),
         required=["S_EPIGASTRIC_PAIN", "S_BELCHING"], cites=["jingui-001-1"],
         tongue_pulse="苔薄白或薄黃；脈弦"),
    # ── heart ──────────────────────────────────────────────────────────────
    dict(id="HT1", zh="心脾兩虛", en="Dual deficiency of heart and spleen", group="heart",
         elements=[("心", "血虛"), ("脾", "氣虛")], principle="補益心脾、養血安神", formulas=["F_GUIPI"],
         weights=dict(S_PALPITATION=3, S_DREAM_MANY=2, S_INSOMNIA_MAINT=2, S_FORGETFUL=3, S_POOR_APPETITE=2, S_LOOSE_STOOL=2,
                      S_FATIGUE=2, S_FACE_SALLOW=2, T_BODY_PALE=2, P_THIN=2, P_DEFICIENT=1),
         against=dict(S_IRRITABLE=1, S_FACE_RED=1, T_BODY_RED=1),
         required=["S_PALPITATION", "S_FORGETFUL"], cites=[],
         tongue_pulse="舌淡；脈細弱"),
    dict(id="HT2", zh="心腎不交（陰虛火旺）", en="Disharmony between heart and kidney (yin deficiency with effulgent fire)", group="heart",
         elements=[("心", "火"), ("腎", "陰虛")], principle="滋陰降火、交通心腎", formulas=["F_HUANGLIANEJIAO", "F_TIANWANG"],
         weights=dict(S_RESTLESS_NO_SLEEP=3, S_PALPITATION=2, S_LOW_BACK_SORE=2, S_HEAT_PALMS_SOLES=3, S_NIGHT_SWEAT=2,
                      S_TINNITUS_THIN=2, S_SEMINAL_EMISSION=1, S_DRY_MOUTH_THROAT=1, S_FORGETFUL=1, T_BODY_RED=2, T_TIP_RED=3,
                      T_COAT_PEELED_ALL=2, T_ROOT_COAT_PEELED=2, P_THIN=1, P_RAPID=2),
         against=dict(S_FEAR_COLD=2, T_BODY_PALE=2, T_COAT_WHITE_GREASY=1),
         required=["S_RESTLESS_NO_SLEEP", "S_HEAT_PALMS_SOLES"], cites=["shanghan-303"],
         tongue_pulse="舌紅少苔；脈細數"),
    dict(id="HT3", zh="痰熱擾心", en="Phlegm-heat harassing the heart", group="heart",
         elements=[("心", "痰"), ("心", "火")], principle="清熱化痰、和胃安神", formulas=["F_WENDAN"],
         weights=dict(S_INSOMNIA_ONSET=2, S_DREAM_MANY=2, S_STARTLE=3, S_CHEST_OPPRESSION=2, S_PHLEGM_COPIOUS=2, S_BITTER_MOUTH=2,
                      S_RESTLESS_NO_SLEEP=2, S_NAUSEA=1, T_COAT_YELLOW_GREASY=3, T_BODY_RED=1, T_TIP_RED=1, P_SLIPPERY=2, P_RAPID=2),
         against=dict(S_FEAR_COLD=1, T_COAT_PEELED_ALL=2),
         required=["S_STARTLE", "T_COAT_YELLOW_GREASY"], cites=["lingshu-071-1", "suwen-034-1"],
         tongue_pulse="舌紅苔黃膩；脈滑數"),
    # ── lung ───────────────────────────────────────────────────────────────
    dict(id="LG1", zh="肺氣虛（衛表不固）", en="Lung qi deficiency (insecure defensive exterior)", group="lung",
         elements=[("肺", "氣虛")], principle="益氣固表", formulas=["F_YUPINGFENG"],
         weights=dict(S_SHORT_BREATH=3, S_LOW_VOICE=2, S_SPONTANEOUS_SWEAT=3, S_AVERSION_WIND=2, S_EASY_COLD=3, S_FATIGUE=1,
                      S_COUGH_WEAK=1, T_BODY_PALE=1, T_COAT_THIN_WHITE=1, P_DEFICIENT=2),
         against=dict(S_NIGHT_SWEAT=1, T_BODY_RED=2),
         required=["S_EASY_COLD", "S_SHORT_BREATH"], cites=[],
         tongue_pulse="舌淡苔白；脈弱"),
    dict(id="LG2", zh="肺陰虛", en="Lung yin deficiency", group="lung",
         elements=[("肺", "陰虛")], principle="養陰潤肺", formulas=["F_MAIMENDONG", "F_SHASHEN"],
         weights=dict(S_COUGH_DRY=3, S_DRY_MOUTH_THROAT=2, S_NIGHT_SWEAT=2, S_TIDAL_FEVER=2, S_HEAT_PALMS_SOLES=2, S_HOARSE=2,
                      S_DRY_THROAT=1, T_BODY_RED=2, T_TIP_COAT_PEELED=2, T_COAT_PEELED_ALL=2, T_COAT_DRY=1, P_THIN=1, P_RAPID=1),
         against=dict(S_PHLEGM_COPIOUS=2, S_FEAR_COLD=1, T_COAT_WHITE_GREASY=2),
         required=["S_COUGH_DRY"], cites=["jingui-007-1"],
         tongue_pulse="舌紅少津；脈細數"),
    # ── kidney ─────────────────────────────────────────────────────────────
    dict(id="KD1", zh="腎陰虛", en="Kidney yin deficiency", group="kidney",
         elements=[("腎", "陰虛")], principle="滋陰補腎", formulas=["F_LIUWEI"],
         weights=dict(S_LOW_BACK_SORE=3, S_TINNITUS_THIN=2, S_HEAD_DIZZY=1, S_HEAT_PALMS_SOLES=3, S_TIDAL_FEVER=1, S_NIGHT_SWEAT=2,
                      S_DRY_MOUTH_THROAT=2, S_SEMINAL_EMISSION=1, T_BODY_RED=2, T_ROOT_COAT_PEELED=3, T_COAT_PEELED_ALL=2,
                      T_CRACKS_ALL=1, P_THIN=2, P_RAPID=1),
         against=dict(S_FEAR_COLD=2, T_COAT_WHITE_GREASY=1, T_BODY_PALE=2),
         required=["S_LOW_BACK_SORE", "T_ROOT_COAT_PEELED"], cites=[],
         tongue_pulse="舌紅少苔；脈細數"),
    dict(id="KD2", zh="腎陽虛", en="Kidney yang deficiency", group="kidney",
         elements=[("腎", "陽虛"), ("腎", "寒")], principle="溫補腎陽", formulas=["F_SHENQI", "F_YOUGUI"],
         weights=dict(S_LOW_BACK_COLD=3, S_FEAR_COLD=3, S_COLD_LIMBS=2, S_FREQUENT_NOCTURIA=3, S_SPIRIT_WITHDRAWN=2, S_EDEMA=1,
                      S_URINE_CLEAR_LONG=2, S_LOOSE_STOOL=1, S_FATIGUE=1, T_BODY_PALE_SWOLLEN=2, T_COAT_SLIPPERY=1, P_SINK=2,
                      P_SLOW=1, P_DEFICIENT=2),
         against=dict(S_HEAT_PALMS_SOLES=3, S_THIRST_COLD_DRINK=2, T_BODY_RED=2),
         required=["S_LOW_BACK_COLD", "S_FEAR_COLD", "S_FREQUENT_NOCTURIA"], cites=["jingui-006-2"],
         tongue_pulse="舌淡胖苔白；脈沉細（尺弱）"),
    # ── qi-blood ───────────────────────────────────────────────────────────
    dict(id="QB1", zh="氣血兩虛", en="Dual deficiency of qi and blood", group="qi-blood",
         elements=[("脾", "氣虛"), ("心", "血虛")], principle="益氣補血", formulas=["F_BAZHEN"],
         weights=dict(S_FATIGUE=3, S_HEAD_DIZZY=2, S_PALPITATION=2, S_FACE_PALE=2, S_FACE_SALLOW=1, S_SHORT_BREATH=2,
                      S_LIPS_NAILS_PALE=2, S_LAZY_SPEAK=1, S_MENSES_SCANTY_PALE=1, S_INSOMNIA_MAINT=1, T_BODY_PALE=3,
                      T_TENDER=1, P_THIN=2, P_DEFICIENT=2),
         against=dict(S_FACE_RED=1, S_IRRITABLE=1, T_BODY_RED=1),
         required=["S_FATIGUE"], cites=[],
         tongue_pulse="舌淡嫩；脈細弱"),
    dict(id="QB2", zh="血瘀", en="Blood stasis", group="qi-blood",
         elements=[("全身", "瘀")], principle="活血化瘀", formulas=["F_XUEFU"],
         weights=dict(S_STABBING_PAIN_FIXED=3, S_PAIN_NIGHT_WORSE=2, S_ABD_REFUSE_PRESS=1, S_FACE_DARK=2, S_LIPS_PURPLE=2,
                      S_SKIN_SQUAMOUS=1, S_MENSES_CLOTS_DARK=3, S_DYSMENORRHEA=2, T_BODY_PURPLE=3, T_ECCHYMOSIS=3,
                      T_SUBLINGUAL_VEINS=2, P_CHOPPY=3),
         against=dict(S_FACE_PALE=1, T_BODY_PALE=1),
         required=["S_STABBING_PAIN_FIXED", "T_ECCHYMOSIS", "T_BODY_PURPLE", "S_MENSES_CLOTS_DARK"], cites=["suwen-062-2"],
         tongue_pulse="舌紫暗或有瘀斑；脈澀"),
]
