"""English rendering of the Chinese-only prose of the knowledge base (task K-13): pattern principles and tongue/pulse notes, formula principles, rationales and cautions, the general regimen.

Machine draft in the sense of docs/i18n-guide.md §4.3: written for this project, in the WHO-style wording of the glossary, and recorded with `en_status: "machine-draft"` until the bilingual
linguistic reviewer (V-06) has checked it. Herbs are named by their pinyin (with the common name where it is unambiguous), as the guide says; the Chinese names stay in the composition tables.
Classical sentences are translated by the project, never copied from a published translation. `validate_kb` checks that every glossary term in a Chinese text appears in its English.
"""

EN_STATUS = "machine-draft"

PATTERN_PRINCIPLE = {
    "EX1": "Release the exterior with pungent-warm herbs; induce sweating",
    "EX2": "Release the muscle layer and the exterior; harmonise the construction and defence",
    "EX3": "Release the exterior with pungent-cool herbs",
    "EX4": "Harmonise the construction and defence",
    "SP1": "Tonify qi and support the spleen",
    "SP2": "Warm the middle and support the spleen",
    "SP3": "Tonify the middle and qi; raise the yang and lift what has sunk",
    "SP4": "Dry dampness and resolve phlegm; regulate qi and harmonise the middle",
    "SP5": "Clear heat and drain dampness",
    "SP6": "Nourish yin and benefit the stomach",
    "LV1": "Soothe the liver and relieve constraint",
    "LV2": "Clear the liver and drain fire",
    "LV3": "Tonify blood and nourish the liver (for restlessness and insomnia from deficiency: nourish blood and calm the spirit)",
    "LV4": "Soothe the liver and harmonise the stomach",
    "HT1": "Tonify the heart and spleen; nourish blood and calm the spirit",
    "HT2": "Enrich yin and bring down fire; restore communication between the heart and kidney",
    "HT3": "Clear heat and resolve phlegm; harmonise the stomach and calm the spirit",
    "LG1": "Tonify qi and secure the exterior",
    "LG2": "Nourish yin and moisten the lung",
    "KD1": "Enrich yin and tonify the kidney",
    "KD2": "Warm and tonify the kidney yang",
    "QB1": "Tonify qi and blood",
    "QB2": "Invigorate blood and dispel stasis",
}

PATTERN_TONGUE_PULSE = {
    "EX1": "Thin white coating; floating, tight pulse",
    "EX2": "Thin white coating; floating, moderate pulse",
    "EX3": "Tongue edges and tip red with a thin yellow coating; floating, rapid pulse",
    "EX4": "Thin white coating; moderate pulse",
    "SP1": "Pale tongue with a white coating, often swollen with tooth marks; moderate, weak pulse",
    "SP2": "Pale, swollen tongue with a white, slippery coating; deep, slow pulse",
    "SP3": "Pale tongue; weak pulse",
    "SP4": "Swollen tongue with a greasy coating; slippery pulse",
    "SP5": "Red tongue with a yellow, greasy coating; slippery, rapid pulse",
    "SP6": "Red tongue lacking moisture; thin, rapid pulse",
    "LV1": "Thin white coating; wiry pulse",
    "LV2": "Red tongue with a yellow coating; wiry, rapid pulse",
    "LV3": "Pale tongue; thin pulse",
    "LV4": "Thin white or thin yellow coating; wiry pulse",
    "HT1": "Pale tongue; thin, weak pulse",
    "HT2": "Red tongue with a scanty coating; thin, rapid pulse",
    "HT3": "Red tongue with a yellow, greasy coating; slippery, rapid pulse",
    "LG1": "Pale tongue with a white coating; weak pulse",
    "LG2": "Red tongue lacking moisture; thin, rapid pulse",
    "KD1": "Red tongue with a scanty coating; thin, rapid pulse",
    "KD2": "Pale, swollen tongue with a white coating; deep, thin pulse (weak at the chi position)",
    "QB1": "Pale, tender tongue; thin, weak pulse",
    "QB2": "Purple or dusky tongue, or with ecchymosis; choppy pulse",
}

# formula id → (principle, rationale, [cautions in the order of the Chinese list])
FORMULA = {
    "F_MAHUANG": ("Release the exterior and induce sweating with pungent-warm herbs; diffuse the lung and calm wheezing",
                  "Mahuang induces sweating, releases the exterior, diffuses the lung and calms wheezing, and is the sovereign; guizhi helps mahuang to sweat and warms and frees the channels, as minister; xingren (apricot kernel) directs lung qi downward and helps to calm wheezing, as assistant; prepared licorice harmonises the other herbs, as envoy.",
                  ["Not for a weak exterior with spontaneous sweating, a weak constitution with an external illness, blood deficiency or blood loss", "Use with caution with high blood pressure, palpitations or an overactive thyroid", "Stop once the illness is relieved; do not sweat the person too much"]),
    "F_GUIZHI": ("Release the muscle layer and the exterior; harmonise the construction and defence",
                 "Guizhi releases the muscle layer and the exterior and warms the defensive yang, as sovereign; shaoyao (peony) boosts yin and astringes the construction, as minister — together guizhi and shaoyao disperse and astringe, and so harmonise construction and defence; shengjiang (fresh ginger) helps guizhi to release the muscle layer and dazao (jujube) helps shaoyao to boost the construction, as assistants; prepared licorice harmonises the other herbs, as envoy. After the dose, sip hot thin porridge to support the formula's action.",
                 ["Not for an excess exterior without sweating", "Not suited to warm-heat illnesses or yin deficiency with fire", "After the dose avoid raw and cold, sticky and slippery foods, meat, noodles, strong-smelling vegetables, alcohol and dairy (the original instructions)"]),
    "F_YINQIAO": ("Release the exterior with pungent-cool herbs; clear heat and resolve toxin",
                  "Jinyinhua (honeysuckle) and lianqiao (forsythia) are pungent-cool, thrust out the pathogen and clear heat and toxin, as sovereigns; bohe (mint) and niubangzi disperse wind and heat, clear the head and eyes and ease the throat, while jingjiesui and dandouchi disperse and release the exterior, as ministers; zhuye (bamboo leaf) clears heat in the upper burner, lugen (reed rhizome) clears heat and generates fluids, and jiegeng (platycodon) diffuses the lung and eases the throat, as assistants; licorice harmonises the other herbs, as envoy.",
                  ["Not for an external illness from wind-cold with no sweating and aversion to cold", "Do not boil for long (it is aromatic and light; \"overcooked, its flavour turns heavy and enters the middle burner\")", "Use with caution if the spleen and stomach are weak and cold"]),
    "F_SANGJU": ("Disperse wind and clear heat; diffuse the lung and relieve cough",
                 "Sangye (mulberry leaf) and juhua (chrysanthemum) disperse wind and heat and diffuse the lung to relieve cough, as sovereigns; bohe helps to disperse wind, while xingren and jiegeng diffuse and direct downward the lung qi, as minister-assistants; lianqiao clears heat and lugen clears heat and generates fluids, as assistants; licorice harmonises the other herbs, as envoy.",
                 ["Not for cough from wind-cold", "Use with caution if the spleen and stomach are weak and cold"]),
    "F_SIJUNZI": ("Tonify qi and support the spleen",
                  "Renshen (ginseng) strongly tonifies the source qi and supports the spleen and stomach, as sovereign; baizhu dries dampness and supports the spleen, as minister; fuling (poria) drains dampness and supports the spleen, as assistant, and together with baizhu strengthens the removal of dampness; prepared licorice tonifies qi, harmonises the middle and harmonises the other herbs, as envoy.",
                  ["Not for excess or heat patterns, or yin deficiency with fire", "Renshen should not be used with lilu or wulingzhi"]),
    "F_SHENLING": ("Tonify qi and support the spleen; drain dampness and stop diarrhoea",
                   "Renshen, baizhu and fuling tonify qi, support the spleen and drain dampness, as sovereigns; shanyao and lianzi (lotus seed) help the sovereigns to support the spleen and tonify qi and also stop diarrhoea, as ministers; baibiandou (lablab bean) and yiyiren (coix seed) support the spleen and drain dampness, sharen (amomum) wakes the spleen, harmonises the stomach and moves qi, and jiegeng diffuses the lung and carries the herbs upward, as assistants; licorice supports the spleen, harmonises the middle and harmonises the other herbs, as envoy.",
                   ["Not for internal damp-heat or yin deficiency with fire", "Should not be used with lilu or wulingzhi (it contains renshen)"]),
    "F_LIZHONG": ("Warm the middle and dispel cold; tonify qi and support the spleen",
                  "Ganjiang (dried ginger) warms the middle and dispels cold, as sovereign; renshen tonifies qi and supports the spleen, as minister; baizhu dries dampness and supports the spleen, as assistant; prepared licorice tonifies qi, harmonises the middle and harmonises the other herbs, as envoy.",
                  ["Not for yin deficiency with internal heat or excess heat patterns", "Use ganjiang with caution in pregnancy"]),
    "F_BUZHONG": ("Tonify the middle and qi; raise the yang and lift what has sunk",
                  "Huangqi (astragalus) tonifies the middle and qi and raises the yang and secures the exterior, as sovereign; renshen, baizhu and prepared licorice tonify qi and support the spleen, as ministers; danggui nourishes blood and harmonises the construction, and chenpi regulates qi and harmonises the stomach, as assistants; shengma and chaihu raise and lift the clear yang, as envoys (and also as assistants).",
                  ["Not for fever from yin deficiency or intense internal heat", "Not for excess patterns or ascendant liver yang"]),
    "F_ERCHEN": ("Dry dampness and resolve phlegm; regulate qi and harmonise the middle",
                 "Banxia (pinellia) dries dampness, resolves phlegm and directs rebellious qi downward to harmonise the stomach, as sovereign; juhong (orange peel) regulates qi, moves stagnation, dries dampness and resolves phlegm, as minister — together, when qi flows smoothly phlegm descends; fuling supports the spleen and drains dampness, as assistant; prepared licorice harmonises the other herbs, as envoy.",
                 ["Not for dry cough from yin deficiency, vomiting of blood or wasting-thirst", "Banxia must be processed; use with caution in pregnancy", "Should not be used with wutou-type herbs"]),
    "F_PINGWEI": ("Dry dampness and move the spleen; move qi and harmonise the stomach",
                  "Cangzhu dries dampness and moves the spleen, as sovereign; houpo (magnolia bark) moves qi, relieves fullness and dries dampness, as minister; chenpi regulates qi and moves stagnation, as assistant; prepared licorice harmonises the other herbs, as envoy.",
                  ["Not for qi stagnation with yin deficiency, or a weak spleen and stomach", "Use with caution in pregnancy"]),
    "F_LINGGUIZHUGAN": ("Warm the yang and transform rheum; support the spleen and drain dampness",
                        "Fuling supports the spleen, drains dampness and transforms rheum, as sovereign; guizhi warms the yang, transforms qi and calms upward surging, as minister; baizhu supports the spleen and dries dampness, as assistant; prepared licorice tonifies qi, harmonises the middle and harmonises the other herbs, as envoy. The Jingui says: \"For those ill with phlegm-rheum, harmonise it with warming medicine.\"",
                        ["Not for yin deficiency with fire or phlegm-heat", "Use guizhi with caution in pregnancy"]),
    "F_SANREN": ("Diffuse and free the qi movement; clear and drain damp-heat",
                 "Xingren diffuses lung qi in the upper burner, baikouren (cardamom) transforms dampness with its fragrance and moves qi to ease the middle, and yiyiren drains dampness downward with its sweet blandness; together the three are the sovereigns, diffusing above, freeing the middle and draining below; huashi, tongcao and zhuye clear heat and drain dampness, as ministers; houpo and banxia move qi, dry dampness and disperse fullness, as assistants.",
                 ["Not for yin deficiency with fluid damage, or without damp-heat", "Use with caution in pregnancy (yiyiren, huashi, banxia)", "Should not be used with wutou-type herbs (it contains banxia)"]),
    "F_GANLU": ("Drain dampness and transform turbidity; clear heat and resolve toxin",
                "Huashi drains water and clears heat, yinchen clears heat, drains dampness and relieves jaundice, and huangqin clears heat and dries dampness; together they are the sovereigns; shichangpu, chuanbeimu and mutong transform dampness and phlegm and lead heat downward, as ministers; huoxiang, baidoukou and bohe transform turbidity with their fragrance, while lianqiao and shegan clear heat, resolve toxin and ease the throat, as assistants.",
                ["In the original, \"mutong\" must be chuanmutong or tongcao — never guanmutong, which contains aristolochic acid", "Not for cold-damp patterns or yin deficiency", "Use with caution in pregnancy"]),
    "F_YIWEI": ("Nourish yin and benefit the stomach",
                "Shengdihuang (rehmannia) and maidong are sweet-cold, nourish yin, clear heat and generate fluids, as sovereigns; shashen and yuzhu nourish yin, generate fluids and benefit the stomach, as ministers; rock sugar moistens the lung and stomach and harmonises the other herbs, as assistant.",
                ["Not for a weak, cold spleen and stomach, or for dampness and phlegm-dampness", "People with diabetes should use the rock sugar with caution"]),
    "F_XIAOYAO": ("Soothe the liver and relieve constraint; nourish blood and support the spleen",
                  "Chaihu (bupleurum) soothes the liver and relieves constraint, as sovereign; danggui and baishao (white peony) nourish blood and soften the liver, as ministers — with chaihu they supplement the liver's substance and support its function; baizhu and fuling support the spleen and dispel dampness, bohe disperses suppressed qi and carries through the liver channel, and weijiang (roasted ginger) warms the stomach and harmonises the middle, as assistants; prepared licorice harmonises the other herbs, as envoy.",
                  ["Use with caution with ascendant liver yang or yin deficiency with fire", "Use with caution in pregnancy (it contains danggui)", "Keep the mood at ease while taking it"]),
    "F_CHAIHUSHUGAN": ("Soothe the liver and regulate qi; invigorate blood and relieve pain",
                       "Chaihu soothes the liver and relieves constraint, as sovereign; xiangfu regulates qi, soothes the liver and relieves pain, and chuanxiong invigorates blood, moves qi and relieves pain, as ministers; chenpi and zhiqiao regulate qi and move stagnation, while shaoyao and licorice nourish blood, soften the liver and relieve spasm and pain, as assistants and envoys.",
                       ["Not for yin deficiency with fire, or hypochondriac pain from liver blood deficiency", "Use with caution in pregnancy (chuanxiong, zhiqiao)"]),
    "F_YUEJU": ("Move qi and relieve constraint (the six constraints: qi, blood, phlegm, fire, dampness, food)",
                "Xiangfu moves qi and relieves qi constraint, as sovereign; chuanxiong invigorates blood and moves qi to relieve blood constraint, cangzhu dries dampness and moves the spleen to relieve damp constraint, shenqu (fermented leaven) disperses food and harmonises the stomach to relieve food constraint, and zhizi (gardenia) clears heat and drains fire to relieve fire constraint; phlegm constraint comes from qi stagnation and gathered dampness, so it clears when the other constraints are relieved.",
                ["Not to be used alone for constraint and stagnation from deficiency", "Use with caution in pregnancy (chuanxiong)"]),
    "F_LONGDAN": ("Clear and drain excess fire of the liver and gallbladder; clear and drain damp-heat of the liver channel",
                  "Longdancao (gentian) is intensely bitter and cold, drains excess fire of the liver and gallbladder and drains damp-heat of the liver channel, as sovereign; huangqin and zhizi are bitter-cold and drain fire, as ministers; zexie (alisma), mutong and cheqianzi clear and drain damp-heat, while danggui and shengdihuang nourish blood and enrich yin to protect the liver yin, as assistants; chaihu soothes the liver and guides the herbs to the channel, and licorice harmonises the other herbs, as envoys.",
                  ["Bitter and cold and harsh: it easily harms the spleen and stomach, so do not take it for long", "Not for a weak, cold spleen and stomach, or yin deficiency with hyperactive yang", "Mutong must be chuanmutong; never guanmutong", "Use with caution in pregnancy"]),
    "F_SIWU": ("Tonify blood and regulate blood",
               "Shudihuang (cooked rehmannia) enriches yin and nourishes blood, as sovereign; danggui tonifies blood, nourishes the liver, harmonises blood and regulates menstruation, as minister; baishao nourishes blood, softens the liver and harmonises the construction, as assistant; chuanxiong invigorates blood and moves qi and so frees qi and blood, as envoy, so that the tonification does not stagnate.",
               ["Use with caution if the spleen and stomach are weak, with poor appetite and loose stools", "Use with caution in pregnancy (chuanxiong, danggui)"]),
    "F_SUANZAOREN": ("Nourish blood and calm the spirit; clear heat and relieve restlessness",
                     "Suanzaoren (jujube seed) nourishes blood, tonifies the liver and quiets the heart and spirit, as sovereign; fuling quiets the heart and spirit, as minister; zhimu enriches yin, clears heat, relieves restlessness and calms the spirit, and chuanxiong regulates blood and soothes the liver, as assistants; licorice harmonises the middle, relieves urgency and harmonises the other herbs, as envoy.",
                     ["Use with caution in pregnancy (chuanxiong)", "Use suanzaoren with caution with excess pathogen or constrained fire", "Avoid coffee and strong tea while taking it"]),
    "F_GUIPI": ("Tonify qi and blood; support the spleen and nourish the heart",
                "Huangqi tonifies spleen qi, and longyanrou (longan flesh) tonifies the heart and spleen, nourishes blood and calms the spirit; together they are the sovereigns; renshen and baizhu help huangqi to tonify spleen qi, danggui helps longyanrou to nourish blood, and suanzaoren, fushen and yuanzhi quiet the heart and spirit, as ministers; muxiang regulates qi and wakes the spleen so that the tonification does not stagnate, as assistant; prepared licorice harmonises the other herbs, as envoy.",
                ["Not for yin deficiency with fire, or with abundant internal phlegm-dampness", "Use with caution in pregnancy (danggui)", "Pause during an external illness with fever"]),
    "F_HUANGLIANEJIAO": ("Enrich yin and bring down fire; restore communication between the heart and kidney",
                         "Huanglian (coptis) clears heart fire and ejiao (donkey-hide gelatin) enriches kidney yin, restoring balance between water and fire, as sovereigns; huangqin helps huanglian to clear fire and shaoyao helps ejiao to enrich yin, as ministers; egg yolk nourishes the heart and enriches yin, calms the spirit and relieves restlessness, as assistant.",
                         ["Not for a weak, cold spleen and stomach, or diarrhoea", "Do not take the bitter-cold herbs for long", "Not for people allergic to egg (the egg yolk)"]),
    "F_TIANWANG": ("Enrich yin and clear heat; nourish blood and calm the spirit",
                   "A large amount of shengdihuang enriches yin and clears heat, as sovereign; tiandong, maidong, suanzaoren and baiziren enrich yin, nourish blood and nourish the heart and spirit, as ministers; xuanshen, danggui, danshen, fuling, renshen, wuweizi and yuanzhi tonify qi and blood and quiet the heart, as assistants; jiegeng carries the herbs upward, as envoy. The original is coated with cinnabar; because it contains mercury, cinnabar is not included in this project's version.",
                   ["The original's cinnabar coating is omitted (it contains mercury)", "Use with caution if the spleen and stomach are weak and cold, or with phlegm-dampness (many of the herbs are rich and cloying)", "Should not be used with lilu (it contains renshen, xuanshen and danshen)"]),
    "F_WENDAN": ("Regulate qi and resolve phlegm; clear the gallbladder and harmonise the stomach",
                 "Banxia dries dampness, resolves phlegm, harmonises the stomach and stops vomiting, as sovereign; zhuru (bamboo shavings) clears heat, resolves phlegm, relieves restlessness and stops vomiting, as minister; zhishi and chenpi regulate qi and resolve phlegm, fuling supports the spleen and drains dampness, and shengjiang and dazao harmonise the middle, as assistants; prepared licorice harmonises the other herbs, as envoy.",
                 ["Not for dry cough from yin deficiency", "Use with caution in pregnancy (banxia, zhishi)"]),
    "F_YUPINGFENG": ("Tonify qi, secure the exterior and stop sweating",
                     "Huangqi tonifies qi, secures the exterior and stops sweating, as sovereign; baizhu supports the spleen and tonifies qi and helps huangqi to secure the exterior, as minister; fangfeng dispels wind and moves to the exterior — together with huangqi it secures the exterior without trapping the pathogen and disperses wind without harming the upright qi, as assistant and envoy.",
                     ["Not for an external wind illness, or an excess exterior without sweating", "Not for night sweating from yin deficiency"]),
    "F_MAIMENDONG": ("Clear and nourish the lung and stomach; direct rebellious qi downward",
                     "A large amount of maidong nourishes yin, generates fluids, nourishes the lung and stomach and clears deficiency fire, as sovereign; banxia directs rebellious qi downward and resolves phlegm — the amount is small and it is paired with a lot of maidong, so it neither dries nor harms yin, as minister; renshen, japonica rice and dazao tonify qi and nourish the stomach, so that the nourished stomach fills the lung qi, as assistants; licorice moistens the lung, eases the throat and harmonises the other herbs, as envoy.",
                     ["Not for cough from phlegm-dampness", "Banxia must be processed", "Should not be used with lilu or wulingzhi (it contains renshen)"]),
    "F_SHASHEN": ("Generate fluids with sweet-cold herbs; clear and nourish the lung and stomach",
                  "Shashen and maidong are sweet-cold, nourish yin, clear the lung and moisten dryness, as sovereigns; yuzhu and tianhuafen help the sovereigns to generate fluids and nourish yin, as ministers; sangye lightly diffuses dry-heat, and baibiandou supports the spleen and harmonises the middle, as assistants; licorice harmonises the other herbs, as envoy.",
                  ["Not for cough from external wind-cold, or for phlegm-dampness", "Should not be used with wutou-type herbs (it contains tianhuafen)", "Should not be used with lilu (it contains shashen)"]),
    "F_LIUWEI": ("Enrich yin and tonify the kidney",
                 "A large amount of shudihuang enriches yin, tonifies the kidney and fills the essence and marrow, as sovereign; shanzhuyu (cornus) nourishes the liver and astringes essence, and shanyao tonifies the spleen and secures essence, as ministers — the three yin are tonified together; zexie drains dampness and turbidity, mudanpi (moutan) clears and drains liver fire, and fuling blandly drains spleen dampness, as assistants — the three draining herbs restrain the stagnation of the three tonifying ones.",
                 ["Use with caution with a weak spleen, loose stools or poor appetite (it is rich and cloying)", "Use mudanpi with caution in pregnancy", "Pause during a cold with fever"]),
    "F_SHENQI": ("Tonify the kidney and support the yang; seek yang within yin",
                 "Fuzi (aconite) and guizhi (later, sometimes rougui) warm and tonify kidney yang and stir kidney qi, as sovereigns, in the sense of \"a small fire generates qi\"; gandihuang, shanzhuyu and shanyao enrich and tonify kidney yin, seeking yang within yin, as ministers; zexie and fuling drain water and dampness, and mudanpi clears and drains liver fire, as assistants.",
                 ["Contains fuzi: toxic, forbidden in pregnancy, must be boiled for a long time and used only under a practitioner's direction", "Not for yin deficiency with fire", "Should not be used with banxia, gualou, beimu, bailian or baiji"]),
    "F_YOUGUI": ("Warm and tonify the kidney yang; fill the essence and marrow",
                 "Fuzi and rougui warm and tonify kidney yang, and lujiaojiao (deer-antler gelatin) warms kidney yang and boosts essence and blood; together they are the sovereigns; shudihuang, shanyao, shanzhuyu and gouqizi enrich yin and benefit the kidney, nourish the liver and tonify the spleen, seeking yang within yin, as ministers; tusizi and duzhong tonify the liver and kidney and strengthen the lower back and knees, and danggui nourishes and harmonises blood, as assistants.",
                 ["Contains fuzi and rougui: fuzi is forbidden in pregnancy, and it must be used only under a practitioner's direction", "Not for yin deficiency with fire, or damp-heat", "Pause during a cold"]),
    "F_BAZHEN": ("Tonify qi and blood",
                 "Renshen and shudihuang tonify qi and nourish blood, as sovereigns; baizhu and fuling support the spleen, and danggui and baishao nourish blood, as ministers; chuanxiong invigorates blood and moves qi so that the tonification does not stagnate, as assistant; prepared licorice, shengjiang and dazao harmonise the middle and the construction, as envoys. It is Sijunzi Tang combined with Siwu Tang.",
                 ["Not for an external illness with fever, or for excess patterns", "Use with caution if the spleen and stomach are weak, with poor appetite and loose stools (it is rich and cloying)", "Use with caution in pregnancy (danggui, chuanxiong)"]),
    "F_XUEFU": ("Invigorate blood and dispel stasis; move qi and relieve pain",
                "Taoren (peach kernel) and honghua (safflower) invigorate blood and dispel stasis, as sovereigns; chishao and chuanxiong help the sovereigns to invigorate blood, and niuxi dispels stasis, frees the vessels and leads blood downward, as ministers; shengdihuang and danggui nourish blood and enrich yin so that dispelling stasis does not harm the upright qi, chaihu and zhiqiao soothe the liver and regulate qi, and jiegeng opens the lung qi and carries the herbs upward, as assistants and envoys; licorice harmonises the other herbs.",
                ["Forbidden in pregnancy and with heavy menstrual bleeding", "Forbidden with anticoagulant medicines or a tendency to bleed", "Not suited when there is no blood stasis"]),
    "F_XIAOCHAIHU": ("Harmonise the shaoyang",
                     "Chaihu thrusts out the pathogen from the shaoyang and clears the channel qi, as sovereign; huangqin clears and drains shaoyang heat, as minister; banxia and shengjiang harmonise the stomach and direct rebellious qi downward, while renshen, prepared licorice and dazao support the upright qi and expel the pathogen, as assistants and envoys. Alternating chills and fever of the shaoyang is an external illness that needs a doctor, so this formula is not offered as self-care in the MVP; it is shown for study only.",
                     ["Alternating chills and fever is a symptom of an external illness and should be assessed by a doctor", "Shown for study only, not as a recommendation"]),
}

GENERAL_TEXT = ("Eat and drink in moderation, keep regular hours and do not overwork; keep the mind quiet and free of craving, so that the true qi follows and the spirit is kept within — how then could illness arise? "
                "Follow the four seasons in nourishing life, as the chapter on regulating the spirit in accordance with the four seasons describes; for food, \"let grains, meat, fruit and vegetables nourish you to the full, without overdoing it, which would harm the right qi\".")
