// The files that make a static host serve the app correctly (task R-04, docs/release-process.md §6): response headers, the single-page-app fallback, a real 404 for unknown
// languages, and /.well-known/security.txt. Written for Cloudflare Pages (decided in TQ1): `_headers`, `_redirects` and a top-level `404.html`. They are generated at build time,
// so the cache rules name the content-hashed knowledge-base chunks of that very build. Pure functions; the Vite plugin in apps/web/vite.config.ts writes them to the output.

/** The Content-Security-Policy directives (tech spec §11). The page's `<meta>` carries all but `frame-ancestors`, which only a header can set. */
export const CSP_DIRECTIVES = ["default-src 'self'", "script-src 'self'", "style-src 'self'", "img-src 'self' data:", "font-src 'self'", "connect-src 'self'", "base-uri 'none'", "form-action 'none'", "object-src 'none'"] as const;
export const cspMeta = (): string => CSP_DIRECTIVES.join("; ");
export const cspHeader = (): string => [...CSP_DIRECTIVES, "frame-ancestors 'none'"].join("; ");

export const IMMUTABLE = "public, max-age=31536000, immutable";
/** Every language segment the host passes to the app: the canonical tags and the lower-case aliases the app redirects to the canonical form (app/routing.ts). Anything else is a 404. */
export const LANGUAGE_SEGMENTS = ["zh-Hant", "zh-Hans", "en", "zh", "zh-tw", "zh-hk", "zh-hant", "zh-hans", "zh-cn", "zh-sg", "en-us", "en-gb"] as const;

export interface HeadersInput {
  /** A dev build or a closed beta must not be indexed (check-release rule 8). */
  readonly noindex: boolean;
  /** File names of the content-hashed knowledge-base chunks, e.g. "core.1a2b3c4d.json". */
  readonly kbChunks: readonly string[];
}

/** The `_headers` file. Cache rules are per exact path and never overlap, because Cloudflare combines the values of every rule that matches. */
export function headersFile(input: HeadersInput): string {
  const security = [
    `Content-Security-Policy: ${cspHeader()}`,
    "X-Content-Type-Options: nosniff",
    "Referrer-Policy: no-referrer",
    "Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()",
    "Cross-Origin-Opener-Policy: same-origin",
    "Strict-Transport-Security: max-age=31536000; includeSubDomains",
    ...(input.noindex ? ["X-Robots-Tag: noindex, nofollow"] : []),
  ];
  const rule = (path: string, lines: readonly string[]): string => [path, ...lines.map((l) => `  ${l}`)].join("\n");
  return [
    "# Generated by scripts/deploy-files.ts — do not edit. Cloudflare Pages applies every matching rule; the cache rules below never overlap.",
    rule("/*", security),
    rule("/assets/*", [`Cache-Control: ${IMMUTABLE}`]),
    ...[...input.kbChunks].sort().map((f) => rule(`/kb/${f}`, [`Cache-Control: ${IMMUTABLE}`])),
    rule("/kb/manifest.json", ["Cache-Control: no-cache"]),
    "",
  ].join("\n\n");
}

/** The `_redirects` file: the app answers under /:lang/…; everything else is a real 404 (served from 404.html because the project has one, which also turns off Pages' blanket SPA mode). */
/** The pseudo-locale segments of the dev build (docs/i18n-guide.md §8); a release build does not know them, so they are a real 404 there. */
export const PSEUDO_SEGMENTS = ["en-XA", "zh-XL", "en-xa", "zh-xl"] as const;

export function redirectsFile(opts: { readonly pseudo?: boolean } = {}): string {
  const rows = [...LANGUAGE_SEGMENTS, ...(opts.pseudo ? PSEUDO_SEGMENTS : [])].flatMap((l) => [[`/${l}`, "/index.html", "200"], [`/${l}/*`, "/index.html", "200"]]);
  return ["# Generated by scripts/deploy-files.ts — do not edit.", ...rows.map((r) => r.join("  ")), ""].join("\n");
}

/** The page served with status 404 for an unknown address: both languages, no script, no style (the CSP allows neither inline). */
export function notFoundPage(): string {
  return `<!doctype html>
<html lang="zh-Hant">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex, nofollow" />
    <title>找不到這個頁面 · Page not found</title>
  </head>
  <body>
    <main>
      <h1>找不到這個頁面</h1>
      <p>網址可能有誤。<a href="/zh-Hant/">回到首頁</a></p>
      <h1 lang="zh-Hans">找不到这个页面</h1>
      <p lang="zh-Hans">网址可能有误。<a href="/zh-Hans/">回到首页</a></p>
      <h1 lang="en">We couldn't find that page</h1>
      <p lang="en">The address may be wrong. <a href="/en/">Back to the start</a></p>
    </main>
  </body>
</html>
`;
}

/** RFC 9116. `Expires` is set at build time to a date at most a year ahead, so a stale file expires on its own. */
export function securityTxt(contact: string, now: Date, policy: string): string {
  const expires = new Date(now.getTime() + 180 * 86_400_000).toISOString().replace(/\.\d{3}Z$/, "Z");
  return `Contact: ${contact}\nExpires: ${expires}\nPreferred-Languages: zh-Hant, en\nPolicy: ${policy}\n`;
}
