// Generate the TypeScript types of @tcm/kb from the JSON Schemas in data/schema (tech spec T8).
//   node scripts/generate-kb-types.ts           write packages/kb/src/generated/*.ts
//   node scripts/generate-kb-types.ts --check   fail if the committed files are stale (CI)
// Length and pattern constraints are validated by the Python build; the generator drops them so the types stay readable
// (fixed-length arrays — minItems = maxItems — are kept and become tuples).
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = join(root, "data", "schema");
const outDir = join(root, "packages", "kb", "src", "generated");
const DROP = new Set(["title", "uniqueItems", "minProperties", "maxProperties", "pattern"]);

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };

/** `isMap`: the node is a `properties` / `$defs` map, whose keys are names (a property may legitimately be called "pattern"), not keywords. */
function prep(node: Json, isMap = false): Json {
  if (Array.isArray(node)) return node.map((n) => prep(n));
  if (node && typeof node === "object") {
    const out: { [k: string]: Json } = {};
    for (const [k, v] of Object.entries(node)) if (isMap || !DROP.has(k)) out[k] = prep(v, !isMap && (k === "properties" || k === "$defs"));
    if (!isMap) {
      if (out.minItems !== undefined && out.minItems !== out.maxItems) delete out.minItems;
      if (out.maxItems !== undefined && out.minItems === undefined) delete out.maxItems;
    }
    return out;
  }
  return node;
}

const pascal = (stem: string): string => stem.split("-").map((w) => w[0]!.toUpperCase() + w.slice(1)).join("");

const check = process.argv.includes("--check");
const stale: string[] = [];
const stems = readdirSync(schemaDir).filter((f) => f.endsWith(".schema.json")).map((f) => f.replace(".schema.json", "")).sort();
if (!check) mkdirSync(outDir, { recursive: true });
for (const stem of stems) {
  const schema = prep(JSON.parse(readFileSync(join(schemaDir, `${stem}.schema.json`), "utf8")) as Json);
  const banner = `// GENERATED by scripts/generate-kb-types.ts from data/schema/${stem}.schema.json — do not edit.`;
  const ts = await compile(schema as never, pascal(stem), { bannerComment: banner, additionalProperties: false, strictIndexSignatures: false });
  const file = join(outDir, `${stem}.ts`);
  if (check) {
    if (!existsSync(file) || readFileSync(file, "utf8") !== ts) stale.push(`${stem}.ts`);
  } else {
    writeFileSync(file, ts);
  }
}
if (check) {
  if (stale.length) {
    console.error(`stale generated types: ${stale.join(", ")} — run \`pnpm generate:kb-types\``);
    process.exit(1);
  }
  console.log(`kb types up to date (${stems.length} files)`);
} else {
  console.log(`generated ${stems.length} type files in packages/kb/src/generated`);
}
