"""Keep the status summary of TASKS.md in sync with its task tables.

    python3 scripts/tasks_summary.py           # print the summary
    python3 scripts/tasks_summary.py --write   # rewrite the block between <!-- SUMMARY --> markers in TASKS.md
"""
from __future__ import annotations

import re
import sys
from collections import OrderedDict
from pathlib import Path

TASKS = Path(__file__).resolve().parents[1] / "TASKS.md"
# A row may end without a closing pipe: notes appended after the last cell (the U rows) are still part of the row.
ROW = re.compile(r"^\|\s*\[(?P<done>[ x])\]\s*\|\s*(?P<id>[A-Z]+-\d+)\s*\|(?P<rest>.*?)\|?\s*$")
SECTION = re.compile(r"^## (?P<key>[A-Z]+)\. (?P<title>.+)$")
TITLES = {"A": "Documentation", "DEC": "Decisions", "K": "Knowledge base", "E": "Engine and packages", "I": "Internationalisation",
          "U": "Web application", "Q": "Quality assurance", "R": "Release and operations", "V": "Review (non-code)", "PF": "Performance (P2)", "PM": "Post-MVP releases"}


def collect(text: str):
    counts: dict[str, dict[str, int]] = OrderedDict()
    prio: dict[str, list[int]] = {"P0": [0, 0], "P1": [0, 0], "P2": [0, 0]}
    for line in text.splitlines():
        m = ROW.match(line)
        if not m:
            continue
        key = m["id"].split("-")[0]
        key = "E" if key == "W" else key   # W-01 (wuxing) is listed under the engine section
        done = m["done"] == "x"
        c = counts.setdefault(key, {"done": 0, "total": 0})
        c["total"] += 1
        c["done"] += done
        pm = re.search(r"\|\s*(P[012])\s*\|", m["rest"] + "|")
        if pm:
            prio[pm[1]][1] += 1
            prio[pm[1]][0] += done
    return counts, prio


def render(counts, prio) -> str:
    rows = ["| Workstream | Done | Total |", "|---|---:|---:|"]
    td = tt = 0
    for k, c in counts.items():
        rows.append(f"| **{k}** {TITLES.get(k, k)} | {c['done']} | {c['total']} |")
        td += c["done"]
        tt += c["total"]
    rows.append(f"| **All** | **{td}** | **{tt}** |")
    rows += ["", "| Priority | Done | Total |", "|---|---:|---:|"]
    for p, (d, t) in prio.items():
        rows.append(f"| {p} | {d} | {t} |")
    rows += ["", "_Generated by `python3 scripts/tasks_summary.py --write`; do not edit by hand._"]
    return "\n".join(rows)


def main() -> int:
    text = TASKS.read_text(encoding="utf-8")
    block = render(*collect(text))
    if "--write" not in sys.argv:
        print(block)
        return 0
    new = re.sub(r"(<!-- SUMMARY -->).*?(<!-- /SUMMARY -->)|<!-- SUMMARY -->", lambda m: f"<!-- SUMMARY -->\n{block}\n<!-- /SUMMARY -->", text, count=1, flags=re.S)
    TASKS.write_text(new, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
