// The verification of the formula library (PM-39; docs/post-mvp/design/prescription-model.md §5): every formula computed from its herbs and
// checked against the knowledge base. Writes docs/formula-verification.md; a failure is a finding for the reviewers, never a change to the data.
//   node scripts/verify-formulas.ts            write the report
//   node scripts/verify-formulas.ts --check    exit 1 when the committed report is not what the data gives (CI, `pnpm test:scripts`)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { DoseBands, Herb, Herbs, KnowledgeBase, Mechanisms, Pairings, Prescription, Processing, Yinjing } from "../packages/kb/src/types.ts";
import { indexKnowledgeBase } from "../packages/kb/src/indexer.ts";
import { rawChunksFromDisk } from "../packages/kb/node/fromDisk.ts";
import { normalize, scorePatterns, synthesizePanel, type PanelVector } from "../packages/engine/src/index.ts";
import { verifyLibrary, type FormulaVerification, type PrescriptionTables } from "../packages/engine/src/prescription/index.ts";
import type { Findings } from "../packages/engine/src/index.ts";
import { PARITY } from "../packages/engine/test/parity.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const REPORT = join(root, "docs", "formula-verification.md");
const data = <T>(rel: string): T => JSON.parse(readFileSync(join(root, "data", rel), "utf8")) as T;

export interface Inputs {
  readonly kb: KnowledgeBase;
  readonly herbs: ReadonlyMap<string, Herb>;
  readonly tables: PrescriptionTables;
  readonly mechanisms: Mechanisms["items"];
  readonly typical: ReadonlyMap<string, PanelVector>;
}

/** The knowledge base as the development profile bundles it, the herb records, the tables, and each pattern's typical patient's deviation. */
export function inputs(): Inputs {
  const kb = indexKnowledgeBase(rawChunksFromDisk("dev"));
  const typical = new Map<string, PanelVector>();
  for (const p of kb.patterns) {
    const c = PARITY.cases.find((x) => x.id === `typical-${p.id}`);
    if (!c) continue;
    const n = normalize(kb, { findings: c.findings as Findings, sex: "female", pregnancy: "no" });
    typical.set(p.id, synthesizePanel(kb, scorePatterns(kb, n), null).observed);
  }
  return {
    kb, typical,
    herbs: new Map(data<Herbs>("herbs/herbs.json").items.map((h) => [h.id, h] as const)),
    tables: {
      params: data<Prescription>("treatment/prescription.json").params, pairings: data<Pairings>("herbs/pairings.json").items,
      processing: data<Processing>("herbs/processing.json").methods, doseBands: data<DoseBands>("herbs/dose-bands.json").items, yinjing: data<Yinjing>("herbs/yinjing.json").channels,
    },
    mechanisms: data<Mechanisms>("treatment/mechanisms.json").items,
  };
}

const f2 = (x: number): string => x.toFixed(2);
const pc = (x: number): string => `${(x * 100).toFixed(0)} %`;

export function render(report: readonly FormulaVerification[], inp: Inputs): string {
  const { kb, herbs, tables } = inp;
  const v = tables.params.verification;
  const formulaName = (id: string): string => kb.formulas.get(id)!.name["zh-Hant"];
  const patternName = (id: string): string => `${id} ${kb.patternById.get(id)?.name["zh-Hant"] ?? ""}`.trim();
  const herbName = (id: string): string => herbs.get(id)?.name["zh-Hant"] ?? id;
  const kinds = new Map<string, number>();
  for (const r of report) for (const f of new Set(r.findings.map((x) => x.split(":")[0]!))) kinds.set(f, (kinds.get(f) ?? 0) + 1);
  const out: string[] = [];
  const w = (line = ""): void => { out.push(line); };
  w("# Formula Library Verification");
  w();
  w("_Generated by `node scripts/verify-formulas.ts` from the knowledge base (`pnpm test:scripts` checks it is current); do not edit by hand._");
  w();
  w("Every formula of the library is computed from its herbs at its own amounts — the herbs' properties, the dose–response, processing and the 七情 of");
  w("[the prescription model](post-mvp/design/prescription-model.md) — and checked against what the knowledge base says of it. **A failure is a finding for the");
  w("clinical and pharmacy reviewers: nothing here changes the data** (decision PD-18). The typical patient of each pattern is the one of the pattern self-test.");
  w();
  w(`Checks and thresholds (\`data/treatment/prescription.json\`): **effect** — the benefit computed from the herbs agrees with the stored \`panel_effect\` (cosine ≥ ${v.cosine_min}); **own patterns** — for each pattern it is listed under, it corrects part of the typical patient's deviation and ranks among the first ${v.rank_max} of the library; **direction** — where the pattern's treatment asks for 升 · 降 · 宣 · 收 (\`data/treatment/mechanisms.json\`), the formula points that way (at least ${v.flat_below}); **roles** — every 君臣佐使 label is supported by a measured reading; **balance** — the burden is at most ${v.burden_ratio_max} of the benefit (weighted); **safety** — no 十八反 or 十九畏 pair and no 相反; a classical 相惡 inside a formula is listed for review.`);
  w();
  const clean = report.filter((r) => r.findings.length === 0).length;
  w(`**${report.length} formulas; ${clean} pass every check.** Formulas with a finding, by kind: ${[...kinds].sort(([a], [b]) => (a < b ? -1 : 1)).map(([k, n]) => `${k} ${n}`).join(" · ") || "none"}.`);
  w();
  w("## 1. Every formula");
  w();
  w("| Formula | Effect (cos) | Own patterns: rank from the herbs (stored) · corrected | Direction | Roles | Burden ÷ benefit | Safety |");
  w("|---|---:|---|---|---:|---:|---|");
  for (const r of report) {
    const ind = r.indications.map((i) => `${i.pass ? "" : "✗ "}${patternName(i.pattern)}: ${i.rank} (${i.rankStored}) · ${pc(i.explained)}`).join("<br>") || "—";
    const dir = r.direction.map((d) => `${d.pass ? "" : "✗ "}${d.need} → ${d.formula >= 0 ? "+" : ""}${f2(d.formula)}`).join("<br>") || "—";
    const saf = r.safety.incompatible.length ? `✗ ${r.safety.incompatible.map(([a, b]) => `${a}–${b}`).join(", ")}` : r.safety.opposed.length ? `相惡 ${r.safety.opposed.length}` : "✓";
    w(`| ${formulaName(r.formula)} | ${r.effect.pass ? "" : "✗ "}${f2(r.effect.cosine)} | ${ind} | ${dir} | ${r.roles.disagreements.length ? "✗ " : ""}${r.roles.agree}/${r.roles.total} | ${r.balance.pass ? "" : "✗ "}${f2(r.balance.ratio)} | ${saf} |`);
  }
  w();
  w("## 2. Roles no reading supports");
  w();
  w("The readings a measurement can give (design §4.4): 主, 助主, 主次 (君, 臣); 佐助, 佐制, 反佐 (佐); 引經, 載藥, 調和, 為之使 (使). A row here is a label the model cannot support — a limit of the model, a gap in a herb's record, or a label to reconsider; the reviewers decide which.");
  w();
  w("| Formula | Herb | Label | What was read | Principal target |");
  w("|---|---|---|---|---|");
  for (const r of report) for (const d of r.roles.disagreements) w(`| ${formulaName(r.formula)} | ${herbName(d.herb)} | ${d.labelled} | ${d.readings.join("、") || "—"} | ${r.roles.principal ?? "—"} |`);
  w();
  w("## 3. A classical 相惡 inside a formula");
  w();
  w("The table of 《本草綱目·序例下》 says one herb takes from the other's effect; the formula combines them anyway. The model weakens the herb by τ, as the table says; whether the classical formula means it (a 相惡 that tempers, as 「惡而不惡」 in 《本草備要》) is for the reviewers.");
  w();
  w("| Formula | Herb | 惡 | Pairing |");
  w("|---|---|---|---|");
  for (const r of report) for (const p of r.safety.opposed) w(`| ${formulaName(r.formula)} | ${herbName(p.herb)} | ${herbName(p.other)} | \`${p.id}\` |`);
  w();
  return out.join("\n");
}

export function build(): string {
  const inp = inputs();
  return render(verifyLibrary(inp), inp);
}

if (import.meta.main) {
  const text = build();
  if (process.argv.includes("--check")) {
    if (readFileSync(REPORT, "utf8") !== text) {
      console.error("docs/formula-verification.md is stale: run `node scripts/verify-formulas.ts`");
      process.exit(1);
    }
    console.log("formula verification report up to date");
  } else {
    writeFileSync(REPORT, text);
    console.log(`wrote ${REPORT}`);
  }
}
